# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from lingya_agents_sdk.models.attachment_extension import AttachmentExtension
from lingya_agents_sdk.models.model_config import ModelConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentsConfig(BaseModel):
    """
    AgentsConfig 的公开协议结构。 / Public contract for agents config.
    """ # noqa: E501
    var_model_config: ModelConfig = Field(description="字段 modelConfig / model config field。", alias="modelConfig")
    support_attachment_ext: List[AttachmentExtension] = Field(description="字段 supportAttachmentExt / support attachment ext field。", alias="supportAttachmentExt")
    max_attachment_count: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 maxAttachmentCount / max attachment count field。", alias="maxAttachmentCount")
    __properties: ClassVar[List[str]] = ["modelConfig", "supportAttachmentExt", "maxAttachmentCount"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentsConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_model_config
        if self.var_model_config:
            _dict['modelConfig'] = self.var_model_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in support_attachment_ext (list)
        _items = []
        if self.support_attachment_ext:
            for _item_support_attachment_ext in self.support_attachment_ext:
                _items.append(_item_support_attachment_ext.to_dict() if _item_support_attachment_ext is not None else None)
            _dict['supportAttachmentExt'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentsConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "modelConfig": ModelConfig.from_dict(obj["modelConfig"]) if obj.get("modelConfig") is not None else None,
            "supportAttachmentExt": [AttachmentExtension.from_dict(_item) for _item in obj["supportAttachmentExt"]] if obj.get("supportAttachmentExt") is not None else None,
            "maxAttachmentCount": obj.get("maxAttachmentCount")
        })
        return _obj


