# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from lingya_agents_sdk.models.ask_user_question_option import AskUserQuestionOption
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AiChatAwaitingInputBriefEvent(BaseModel):
    """
    AiChatAwaitingInputBriefEvent 的公开协议结构。 / Public contract for ai chat awaiting input brief event.
    """ # noqa: E501
    type: StrictStr = Field(description="类型判别值 / type discriminator。")
    tool_call_id: StrictStr = Field(description="字段 toolCallId / tool call id field。", alias="toolCallId")
    tool_name: StrictStr = Field(description="字段 toolName / tool name field。", alias="toolName")
    question_id: StrictStr = Field(description="字段 questionId / question id field。", alias="questionId")
    question: StrictStr = Field(description="字段 question / question field。")
    options: List[AskUserQuestionOption] = Field(description="字段 options / options field。")
    multiple: StrictBool = Field(description="字段 multiple / multiple field。")
    server_now: datetime = Field(description="字段 serverNow / server now field。", alias="serverNow")
    timeout_seconds: Annotated[int, Field(strict=True, ge=1)] = Field(description="字段 timeoutSeconds / timeout seconds field。", alias="timeoutSeconds")
    question_details: Optional[StrictStr] = Field(default=None, description="字段 questionDetails / question details field。", alias="questionDetails")
    __properties: ClassVar[List[str]] = ["type", "toolCallId", "toolName", "questionId", "question", "options", "multiple", "serverNow", "timeoutSeconds", "questionDetails"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['tool-execution-awaiting-user-input']):
            raise ValueError("must be one of enum values ('tool-execution-awaiting-user-input')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AiChatAwaitingInputBriefEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                _items.append(_item_options.to_dict() if _item_options is not None else None)
            _dict['options'] = _items
        # set to None if question_details (nullable) is None
        # and model_fields_set contains the field
        if self.question_details is None and "question_details" in self.model_fields_set:
            _dict['questionDetails'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AiChatAwaitingInputBriefEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "toolCallId": obj.get("toolCallId"),
            "toolName": obj.get("toolName"),
            "questionId": obj.get("questionId"),
            "question": obj.get("question"),
            "options": [AskUserQuestionOption.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None,
            "multiple": obj.get("multiple"),
            "serverNow": obj.get("serverNow"),
            "timeoutSeconds": obj.get("timeoutSeconds"),
            "questionDetails": obj.get("questionDetails")
        })
        return _obj


