# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from lingya_agents_sdk.models.artifact_info import ArtifactInfo
from lingya_agents_sdk.models.conversation_context_usage import ConversationContextUsage
from lingya_agents_sdk.models.usage import Usage
from lingya_agents_sdk.models.workspace_non_file_artifact import WorkspaceNonFileArtifact
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AiChatEndBriefEvent(BaseModel):
    """
    AiChatEndBriefEvent 的公开协议结构。 / Public contract for ai chat end brief event.
    """ # noqa: E501
    type: StrictStr = Field(description="类型判别值 / type discriminator。")
    execution_time_millis: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 executionTimeMillis / execution time millis field。", alias="executionTimeMillis")
    total_usage: Usage = Field(description="字段 totalUsage / total usage field。", alias="totalUsage")
    message_context_usage_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="字段 messageContextUsageRatio / message context usage ratio field。", alias="messageContextUsageRatio")
    context_window_usage: Optional[ConversationContextUsage] = Field(default=None, description="字段 contextWindowUsage / context window usage field。", alias="contextWindowUsage")
    artifacts: List[ArtifactInfo] = Field(description="字段 artifacts / artifacts field。")
    non_file_artifacts: List[WorkspaceNonFileArtifact] = Field(description="字段 nonFileArtifacts / non file artifacts field。", alias="nonFileArtifacts")
    __properties: ClassVar[List[str]] = ["type", "executionTimeMillis", "totalUsage", "messageContextUsageRatio", "contextWindowUsage", "artifacts", "nonFileArtifacts"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['end']):
            raise ValueError("must be one of enum values ('end')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AiChatEndBriefEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of total_usage
        if self.total_usage:
            _dict['totalUsage'] = self.total_usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of context_window_usage
        if self.context_window_usage:
            _dict['contextWindowUsage'] = self.context_window_usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in artifacts (list)
        _items = []
        if self.artifacts:
            for _item_artifacts in self.artifacts:
                _items.append(_item_artifacts.to_dict() if _item_artifacts is not None else None)
            _dict['artifacts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in non_file_artifacts (list)
        _items = []
        if self.non_file_artifacts:
            for _item_non_file_artifacts in self.non_file_artifacts:
                _items.append(_item_non_file_artifacts.to_dict() if _item_non_file_artifacts is not None else None)
            _dict['nonFileArtifacts'] = _items
        # set to None if message_context_usage_ratio (nullable) is None
        # and model_fields_set contains the field
        if self.message_context_usage_ratio is None and "message_context_usage_ratio" in self.model_fields_set:
            _dict['messageContextUsageRatio'] = None

        # set to None if context_window_usage (nullable) is None
        # and model_fields_set contains the field
        if self.context_window_usage is None and "context_window_usage" in self.model_fields_set:
            _dict['contextWindowUsage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AiChatEndBriefEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "executionTimeMillis": obj.get("executionTimeMillis"),
            "totalUsage": Usage.from_dict(obj["totalUsage"]) if obj.get("totalUsage") is not None else None,
            "messageContextUsageRatio": obj.get("messageContextUsageRatio"),
            "contextWindowUsage": ConversationContextUsage.from_dict(obj["contextWindowUsage"]) if obj.get("contextWindowUsage") is not None else None,
            "artifacts": [ArtifactInfo.from_dict(_item) for _item in obj["artifacts"]] if obj.get("artifacts") is not None else None,
            "nonFileArtifacts": [WorkspaceNonFileArtifact.from_dict(_item) for _item in obj["nonFileArtifacts"]] if obj.get("nonFileArtifacts") is not None else None
        })
        return _obj


