"""
Lingya Agents OpenAPI

本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.

The version of the OpenAPI document: 0.1.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, Union

from pydantic import BaseModel, ConfigDict, ValidationError, field_validator
from typing_extensions import Self

from lingya_agents_sdk.models.ai_chat_awaiting_input_brief_event import AiChatAwaitingInputBriefEvent
from lingya_agents_sdk.models.ai_chat_compactor_warning_brief_event import AiChatCompactorWarningBriefEvent
from lingya_agents_sdk.models.ai_chat_compressor_context_end_brief_event import AiChatCompressorContextEndBriefEvent
from lingya_agents_sdk.models.ai_chat_compressor_context_start_brief_event import AiChatCompressorContextStartBriefEvent
from lingya_agents_sdk.models.ai_chat_end_brief_event import AiChatEndBriefEvent
from lingya_agents_sdk.models.ai_chat_error_brief_event import AiChatErrorBriefEvent
from lingya_agents_sdk.models.ai_chat_manual_interrupt_brief_event import AiChatManualInterruptBriefEvent
from lingya_agents_sdk.models.ai_chat_message_brief_event import AiChatMessageBriefEvent
from lingya_agents_sdk.models.ai_chat_request_brief_event import AiChatRequestBriefEvent
from lingya_agents_sdk.models.ai_chat_response_brief_event import AiChatResponseBriefEvent
from lingya_agents_sdk.models.ai_chat_start_brief_event import AiChatStartBriefEvent
from lingya_agents_sdk.models.ai_chat_sub_agent_call_brief_event import AiChatSubAgentCallBriefEvent
from lingya_agents_sdk.models.ai_chat_think_brief_event import AiChatThinkBriefEvent
from lingya_agents_sdk.models.ai_chat_tool_execution_brief_event import AiChatToolExecutionBriefEvent
from lingya_agents_sdk.models.ai_chat_user_query_brief_event import AiChatUserQueryBriefEvent
from lingya_agents_sdk.models.unknown_ai_chat_brief_event import UnknownAiChatBriefEvent

AICHATBRIEFEVENT_ONE_OF_SCHEMAS = [
    "AiChatAwaitingInputBriefEvent",
    "AiChatCompactorWarningBriefEvent",
    "AiChatCompressorContextEndBriefEvent",
    "AiChatCompressorContextStartBriefEvent",
    "AiChatEndBriefEvent",
    "AiChatErrorBriefEvent",
    "AiChatManualInterruptBriefEvent",
    "AiChatMessageBriefEvent",
    "AiChatRequestBriefEvent",
    "AiChatResponseBriefEvent",
    "AiChatStartBriefEvent",
    "AiChatSubAgentCallBriefEvent",
    "AiChatThinkBriefEvent",
    "AiChatToolExecutionBriefEvent",
    "AiChatUserQueryBriefEvent",
    "UnknownAiChatBriefEvent",
]


class AiChatBriefEvent(BaseModel):
    """
    AiChatBriefEvent 的公开协议结构。 / Public contract for ai chat brief event.
    """

    # data type: AiChatUserQueryBriefEvent
    oneof_schema_1_validator: AiChatUserQueryBriefEvent | None = None
    # data type: AiChatCompressorContextStartBriefEvent
    oneof_schema_2_validator: AiChatCompressorContextStartBriefEvent | None = None
    # data type: AiChatCompressorContextEndBriefEvent
    oneof_schema_3_validator: AiChatCompressorContextEndBriefEvent | None = None
    # data type: AiChatCompactorWarningBriefEvent
    oneof_schema_4_validator: AiChatCompactorWarningBriefEvent | None = None
    # data type: AiChatManualInterruptBriefEvent
    oneof_schema_5_validator: AiChatManualInterruptBriefEvent | None = None
    # data type: AiChatErrorBriefEvent
    oneof_schema_6_validator: AiChatErrorBriefEvent | None = None
    # data type: AiChatStartBriefEvent
    oneof_schema_7_validator: AiChatStartBriefEvent | None = None
    # data type: AiChatThinkBriefEvent
    oneof_schema_8_validator: AiChatThinkBriefEvent | None = None
    # data type: AiChatRequestBriefEvent
    oneof_schema_9_validator: AiChatRequestBriefEvent | None = None
    # data type: AiChatResponseBriefEvent
    oneof_schema_10_validator: AiChatResponseBriefEvent | None = None
    # data type: AiChatMessageBriefEvent
    oneof_schema_11_validator: AiChatMessageBriefEvent | None = None
    # data type: AiChatToolExecutionBriefEvent
    oneof_schema_12_validator: AiChatToolExecutionBriefEvent | None = None
    # data type: AiChatSubAgentCallBriefEvent
    oneof_schema_13_validator: AiChatSubAgentCallBriefEvent | None = None
    # data type: AiChatAwaitingInputBriefEvent
    oneof_schema_14_validator: AiChatAwaitingInputBriefEvent | None = None
    # data type: AiChatEndBriefEvent
    oneof_schema_15_validator: AiChatEndBriefEvent | None = None
    # data type: UnknownAiChatBriefEvent
    oneof_schema_16_validator: UnknownAiChatBriefEvent | None = None
    actual_instance: (
        Union[
            AiChatAwaitingInputBriefEvent,
            AiChatCompactorWarningBriefEvent,
            AiChatCompressorContextEndBriefEvent,
            AiChatCompressorContextStartBriefEvent,
            AiChatEndBriefEvent,
            AiChatErrorBriefEvent,
            AiChatManualInterruptBriefEvent,
            AiChatMessageBriefEvent,
            AiChatRequestBriefEvent,
            AiChatResponseBriefEvent,
            AiChatStartBriefEvent,
            AiChatSubAgentCallBriefEvent,
            AiChatThinkBriefEvent,
            AiChatToolExecutionBriefEvent,
            AiChatUserQueryBriefEvent,
            UnknownAiChatBriefEvent,
        ]
        | None
    ) = None
    one_of_schemas: set[str] = {
        "AiChatAwaitingInputBriefEvent",
        "AiChatCompactorWarningBriefEvent",
        "AiChatCompressorContextEndBriefEvent",
        "AiChatCompressorContextStartBriefEvent",
        "AiChatEndBriefEvent",
        "AiChatErrorBriefEvent",
        "AiChatManualInterruptBriefEvent",
        "AiChatMessageBriefEvent",
        "AiChatRequestBriefEvent",
        "AiChatResponseBriefEvent",
        "AiChatStartBriefEvent",
        "AiChatSubAgentCallBriefEvent",
        "AiChatThinkBriefEvent",
        "AiChatToolExecutionBriefEvent",
        "AiChatUserQueryBriefEvent",
        "UnknownAiChatBriefEvent",
    }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    discriminator_value_class_map: dict[str, str] = {}

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        AiChatBriefEvent.model_construct()
        error_messages = []
        match = 0
        # validate data type: AiChatUserQueryBriefEvent
        if not isinstance(v, AiChatUserQueryBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatUserQueryBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatCompressorContextStartBriefEvent
        if not isinstance(v, AiChatCompressorContextStartBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatCompressorContextStartBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatCompressorContextEndBriefEvent
        if not isinstance(v, AiChatCompressorContextEndBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatCompressorContextEndBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatCompactorWarningBriefEvent
        if not isinstance(v, AiChatCompactorWarningBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatCompactorWarningBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatManualInterruptBriefEvent
        if not isinstance(v, AiChatManualInterruptBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatManualInterruptBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatErrorBriefEvent
        if not isinstance(v, AiChatErrorBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatErrorBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatStartBriefEvent
        if not isinstance(v, AiChatStartBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatStartBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatThinkBriefEvent
        if not isinstance(v, AiChatThinkBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatThinkBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatRequestBriefEvent
        if not isinstance(v, AiChatRequestBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatRequestBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatResponseBriefEvent
        if not isinstance(v, AiChatResponseBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatResponseBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatMessageBriefEvent
        if not isinstance(v, AiChatMessageBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatMessageBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatToolExecutionBriefEvent
        if not isinstance(v, AiChatToolExecutionBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatToolExecutionBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatSubAgentCallBriefEvent
        if not isinstance(v, AiChatSubAgentCallBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatSubAgentCallBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatAwaitingInputBriefEvent
        if not isinstance(v, AiChatAwaitingInputBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatAwaitingInputBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatEndBriefEvent
        if not isinstance(v, AiChatEndBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatEndBriefEvent`")
        else:
            match += 1
        # validate data type: UnknownAiChatBriefEvent
        if not isinstance(v, UnknownAiChatBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UnknownAiChatBriefEvent`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in AiChatBriefEvent with oneOf schemas: AiChatAwaitingInputBriefEvent, AiChatCompactorWarningBriefEvent, AiChatCompressorContextEndBriefEvent, AiChatCompressorContextStartBriefEvent, AiChatEndBriefEvent, AiChatErrorBriefEvent, AiChatManualInterruptBriefEvent, AiChatMessageBriefEvent, AiChatRequestBriefEvent, AiChatResponseBriefEvent, AiChatStartBriefEvent, AiChatSubAgentCallBriefEvent, AiChatThinkBriefEvent, AiChatToolExecutionBriefEvent, AiChatUserQueryBriefEvent, UnknownAiChatBriefEvent. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in AiChatBriefEvent with oneOf schemas: AiChatAwaitingInputBriefEvent, AiChatCompactorWarningBriefEvent, AiChatCompressorContextEndBriefEvent, AiChatCompressorContextStartBriefEvent, AiChatEndBriefEvent, AiChatErrorBriefEvent, AiChatManualInterruptBriefEvent, AiChatMessageBriefEvent, AiChatRequestBriefEvent, AiChatResponseBriefEvent, AiChatStartBriefEvent, AiChatSubAgentCallBriefEvent, AiChatThinkBriefEvent, AiChatToolExecutionBriefEvent, AiChatUserQueryBriefEvent, UnknownAiChatBriefEvent. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into AiChatUserQueryBriefEvent
        try:
            instance.actual_instance = AiChatUserQueryBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatCompressorContextStartBriefEvent
        try:
            instance.actual_instance = AiChatCompressorContextStartBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatCompressorContextEndBriefEvent
        try:
            instance.actual_instance = AiChatCompressorContextEndBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatCompactorWarningBriefEvent
        try:
            instance.actual_instance = AiChatCompactorWarningBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatManualInterruptBriefEvent
        try:
            instance.actual_instance = AiChatManualInterruptBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatErrorBriefEvent
        try:
            instance.actual_instance = AiChatErrorBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatStartBriefEvent
        try:
            instance.actual_instance = AiChatStartBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatThinkBriefEvent
        try:
            instance.actual_instance = AiChatThinkBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatRequestBriefEvent
        try:
            instance.actual_instance = AiChatRequestBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatResponseBriefEvent
        try:
            instance.actual_instance = AiChatResponseBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatMessageBriefEvent
        try:
            instance.actual_instance = AiChatMessageBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatToolExecutionBriefEvent
        try:
            instance.actual_instance = AiChatToolExecutionBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatSubAgentCallBriefEvent
        try:
            instance.actual_instance = AiChatSubAgentCallBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatAwaitingInputBriefEvent
        try:
            instance.actual_instance = AiChatAwaitingInputBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatEndBriefEvent
        try:
            instance.actual_instance = AiChatEndBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UnknownAiChatBriefEvent
        try:
            instance.actual_instance = UnknownAiChatBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into AiChatBriefEvent with oneOf schemas: AiChatAwaitingInputBriefEvent, AiChatCompactorWarningBriefEvent, AiChatCompressorContextEndBriefEvent, AiChatCompressorContextStartBriefEvent, AiChatEndBriefEvent, AiChatErrorBriefEvent, AiChatManualInterruptBriefEvent, AiChatMessageBriefEvent, AiChatRequestBriefEvent, AiChatResponseBriefEvent, AiChatStartBriefEvent, AiChatSubAgentCallBriefEvent, AiChatThinkBriefEvent, AiChatToolExecutionBriefEvent, AiChatUserQueryBriefEvent, UnknownAiChatBriefEvent. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into AiChatBriefEvent with oneOf schemas: AiChatAwaitingInputBriefEvent, AiChatCompactorWarningBriefEvent, AiChatCompressorContextEndBriefEvent, AiChatCompressorContextStartBriefEvent, AiChatEndBriefEvent, AiChatErrorBriefEvent, AiChatManualInterruptBriefEvent, AiChatMessageBriefEvent, AiChatRequestBriefEvent, AiChatResponseBriefEvent, AiChatStartBriefEvent, AiChatSubAgentCallBriefEvent, AiChatThinkBriefEvent, AiChatToolExecutionBriefEvent, AiChatUserQueryBriefEvent, UnknownAiChatBriefEvent. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> (
        Union[
            dict[str, Any],
            AiChatAwaitingInputBriefEvent,
            AiChatCompactorWarningBriefEvent,
            AiChatCompressorContextEndBriefEvent,
            AiChatCompressorContextStartBriefEvent,
            AiChatEndBriefEvent,
            AiChatErrorBriefEvent,
            AiChatManualInterruptBriefEvent,
            AiChatMessageBriefEvent,
            AiChatRequestBriefEvent,
            AiChatResponseBriefEvent,
            AiChatStartBriefEvent,
            AiChatSubAgentCallBriefEvent,
            AiChatThinkBriefEvent,
            AiChatToolExecutionBriefEvent,
            AiChatUserQueryBriefEvent,
            UnknownAiChatBriefEvent,
        ]
        | None
    ):
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
