# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from lingya_agents_sdk.models.ai_chat_awaiting_input_brief_event import AiChatAwaitingInputBriefEvent
from lingya_agents_sdk.models.ai_chat_compactor_warning_brief_event import AiChatCompactorWarningBriefEvent
from lingya_agents_sdk.models.ai_chat_compressor_context_end_brief_event import AiChatCompressorContextEndBriefEvent
from lingya_agents_sdk.models.ai_chat_compressor_context_start_brief_event import AiChatCompressorContextStartBriefEvent
from lingya_agents_sdk.models.ai_chat_end_brief_event import AiChatEndBriefEvent
from lingya_agents_sdk.models.ai_chat_error_brief_event import AiChatErrorBriefEvent
from lingya_agents_sdk.models.ai_chat_manual_interrupt_brief_event import AiChatManualInterruptBriefEvent
from lingya_agents_sdk.models.ai_chat_message_brief_event import AiChatMessageBriefEvent
from lingya_agents_sdk.models.ai_chat_request_brief_event import AiChatRequestBriefEvent
from lingya_agents_sdk.models.ai_chat_response_brief_event import AiChatResponseBriefEvent
from lingya_agents_sdk.models.ai_chat_start_brief_event import AiChatStartBriefEvent
from lingya_agents_sdk.models.ai_chat_sub_agent_call_brief_event import AiChatSubAgentCallBriefEvent
from lingya_agents_sdk.models.ai_chat_think_brief_event import AiChatThinkBriefEvent
from lingya_agents_sdk.models.ai_chat_tool_execution_brief_event import AiChatToolExecutionBriefEvent
from lingya_agents_sdk.models.ai_chat_user_query_brief_event import AiChatUserQueryBriefEvent
from lingya_agents_sdk.models.unknown_ai_chat_brief_event import UnknownAiChatBriefEvent
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

AICHATBRIEFEVENT_ONE_OF_SCHEMAS = ["AiChatAwaitingInputBriefEvent", "AiChatCompactorWarningBriefEvent", "AiChatCompressorContextEndBriefEvent", "AiChatCompressorContextStartBriefEvent", "AiChatEndBriefEvent", "AiChatErrorBriefEvent", "AiChatManualInterruptBriefEvent", "AiChatMessageBriefEvent", "AiChatRequestBriefEvent", "AiChatResponseBriefEvent", "AiChatStartBriefEvent", "AiChatSubAgentCallBriefEvent", "AiChatThinkBriefEvent", "AiChatToolExecutionBriefEvent", "AiChatUserQueryBriefEvent", "UnknownAiChatBriefEvent"]

class AiChatBriefEvent(BaseModel):
    """
    AiChatBriefEvent 的公开协议结构。 / Public contract for ai chat brief event.
    """
    # data type: AiChatUserQueryBriefEvent
    oneof_schema_1_validator: Optional[AiChatUserQueryBriefEvent] = None
    # data type: AiChatCompressorContextStartBriefEvent
    oneof_schema_2_validator: Optional[AiChatCompressorContextStartBriefEvent] = None
    # data type: AiChatCompressorContextEndBriefEvent
    oneof_schema_3_validator: Optional[AiChatCompressorContextEndBriefEvent] = None
    # data type: AiChatCompactorWarningBriefEvent
    oneof_schema_4_validator: Optional[AiChatCompactorWarningBriefEvent] = None
    # data type: AiChatManualInterruptBriefEvent
    oneof_schema_5_validator: Optional[AiChatManualInterruptBriefEvent] = None
    # data type: AiChatErrorBriefEvent
    oneof_schema_6_validator: Optional[AiChatErrorBriefEvent] = None
    # data type: AiChatStartBriefEvent
    oneof_schema_7_validator: Optional[AiChatStartBriefEvent] = None
    # data type: AiChatThinkBriefEvent
    oneof_schema_8_validator: Optional[AiChatThinkBriefEvent] = None
    # data type: AiChatRequestBriefEvent
    oneof_schema_9_validator: Optional[AiChatRequestBriefEvent] = None
    # data type: AiChatResponseBriefEvent
    oneof_schema_10_validator: Optional[AiChatResponseBriefEvent] = None
    # data type: AiChatMessageBriefEvent
    oneof_schema_11_validator: Optional[AiChatMessageBriefEvent] = None
    # data type: AiChatToolExecutionBriefEvent
    oneof_schema_12_validator: Optional[AiChatToolExecutionBriefEvent] = None
    # data type: AiChatSubAgentCallBriefEvent
    oneof_schema_13_validator: Optional[AiChatSubAgentCallBriefEvent] = None
    # data type: AiChatAwaitingInputBriefEvent
    oneof_schema_14_validator: Optional[AiChatAwaitingInputBriefEvent] = None
    # data type: AiChatEndBriefEvent
    oneof_schema_15_validator: Optional[AiChatEndBriefEvent] = None
    # data type: UnknownAiChatBriefEvent
    oneof_schema_16_validator: Optional[UnknownAiChatBriefEvent] = None
    actual_instance: Optional[Union[AiChatAwaitingInputBriefEvent, AiChatCompactorWarningBriefEvent, AiChatCompressorContextEndBriefEvent, AiChatCompressorContextStartBriefEvent, AiChatEndBriefEvent, AiChatErrorBriefEvent, AiChatManualInterruptBriefEvent, AiChatMessageBriefEvent, AiChatRequestBriefEvent, AiChatResponseBriefEvent, AiChatStartBriefEvent, AiChatSubAgentCallBriefEvent, AiChatThinkBriefEvent, AiChatToolExecutionBriefEvent, AiChatUserQueryBriefEvent, UnknownAiChatBriefEvent]] = None
    one_of_schemas: Set[str] = { "AiChatAwaitingInputBriefEvent", "AiChatCompactorWarningBriefEvent", "AiChatCompressorContextEndBriefEvent", "AiChatCompressorContextStartBriefEvent", "AiChatEndBriefEvent", "AiChatErrorBriefEvent", "AiChatManualInterruptBriefEvent", "AiChatMessageBriefEvent", "AiChatRequestBriefEvent", "AiChatResponseBriefEvent", "AiChatStartBriefEvent", "AiChatSubAgentCallBriefEvent", "AiChatThinkBriefEvent", "AiChatToolExecutionBriefEvent", "AiChatUserQueryBriefEvent", "UnknownAiChatBriefEvent" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = AiChatBriefEvent.model_construct()
        error_messages = []
        match = 0
        # validate data type: AiChatUserQueryBriefEvent
        if not isinstance(v, AiChatUserQueryBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatUserQueryBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatCompressorContextStartBriefEvent
        if not isinstance(v, AiChatCompressorContextStartBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatCompressorContextStartBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatCompressorContextEndBriefEvent
        if not isinstance(v, AiChatCompressorContextEndBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatCompressorContextEndBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatCompactorWarningBriefEvent
        if not isinstance(v, AiChatCompactorWarningBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatCompactorWarningBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatManualInterruptBriefEvent
        if not isinstance(v, AiChatManualInterruptBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatManualInterruptBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatErrorBriefEvent
        if not isinstance(v, AiChatErrorBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatErrorBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatStartBriefEvent
        if not isinstance(v, AiChatStartBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatStartBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatThinkBriefEvent
        if not isinstance(v, AiChatThinkBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatThinkBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatRequestBriefEvent
        if not isinstance(v, AiChatRequestBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatRequestBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatResponseBriefEvent
        if not isinstance(v, AiChatResponseBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatResponseBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatMessageBriefEvent
        if not isinstance(v, AiChatMessageBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatMessageBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatToolExecutionBriefEvent
        if not isinstance(v, AiChatToolExecutionBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatToolExecutionBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatSubAgentCallBriefEvent
        if not isinstance(v, AiChatSubAgentCallBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatSubAgentCallBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatAwaitingInputBriefEvent
        if not isinstance(v, AiChatAwaitingInputBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatAwaitingInputBriefEvent`")
        else:
            match += 1
        # validate data type: AiChatEndBriefEvent
        if not isinstance(v, AiChatEndBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AiChatEndBriefEvent`")
        else:
            match += 1
        # validate data type: UnknownAiChatBriefEvent
        if not isinstance(v, UnknownAiChatBriefEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UnknownAiChatBriefEvent`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in AiChatBriefEvent with oneOf schemas: AiChatAwaitingInputBriefEvent, AiChatCompactorWarningBriefEvent, AiChatCompressorContextEndBriefEvent, AiChatCompressorContextStartBriefEvent, AiChatEndBriefEvent, AiChatErrorBriefEvent, AiChatManualInterruptBriefEvent, AiChatMessageBriefEvent, AiChatRequestBriefEvent, AiChatResponseBriefEvent, AiChatStartBriefEvent, AiChatSubAgentCallBriefEvent, AiChatThinkBriefEvent, AiChatToolExecutionBriefEvent, AiChatUserQueryBriefEvent, UnknownAiChatBriefEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in AiChatBriefEvent with oneOf schemas: AiChatAwaitingInputBriefEvent, AiChatCompactorWarningBriefEvent, AiChatCompressorContextEndBriefEvent, AiChatCompressorContextStartBriefEvent, AiChatEndBriefEvent, AiChatErrorBriefEvent, AiChatManualInterruptBriefEvent, AiChatMessageBriefEvent, AiChatRequestBriefEvent, AiChatResponseBriefEvent, AiChatStartBriefEvent, AiChatSubAgentCallBriefEvent, AiChatThinkBriefEvent, AiChatToolExecutionBriefEvent, AiChatUserQueryBriefEvent, UnknownAiChatBriefEvent. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into AiChatUserQueryBriefEvent
        try:
            instance.actual_instance = AiChatUserQueryBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatCompressorContextStartBriefEvent
        try:
            instance.actual_instance = AiChatCompressorContextStartBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatCompressorContextEndBriefEvent
        try:
            instance.actual_instance = AiChatCompressorContextEndBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatCompactorWarningBriefEvent
        try:
            instance.actual_instance = AiChatCompactorWarningBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatManualInterruptBriefEvent
        try:
            instance.actual_instance = AiChatManualInterruptBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatErrorBriefEvent
        try:
            instance.actual_instance = AiChatErrorBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatStartBriefEvent
        try:
            instance.actual_instance = AiChatStartBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatThinkBriefEvent
        try:
            instance.actual_instance = AiChatThinkBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatRequestBriefEvent
        try:
            instance.actual_instance = AiChatRequestBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatResponseBriefEvent
        try:
            instance.actual_instance = AiChatResponseBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatMessageBriefEvent
        try:
            instance.actual_instance = AiChatMessageBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatToolExecutionBriefEvent
        try:
            instance.actual_instance = AiChatToolExecutionBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatSubAgentCallBriefEvent
        try:
            instance.actual_instance = AiChatSubAgentCallBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatAwaitingInputBriefEvent
        try:
            instance.actual_instance = AiChatAwaitingInputBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AiChatEndBriefEvent
        try:
            instance.actual_instance = AiChatEndBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UnknownAiChatBriefEvent
        try:
            instance.actual_instance = UnknownAiChatBriefEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into AiChatBriefEvent with oneOf schemas: AiChatAwaitingInputBriefEvent, AiChatCompactorWarningBriefEvent, AiChatCompressorContextEndBriefEvent, AiChatCompressorContextStartBriefEvent, AiChatEndBriefEvent, AiChatErrorBriefEvent, AiChatManualInterruptBriefEvent, AiChatMessageBriefEvent, AiChatRequestBriefEvent, AiChatResponseBriefEvent, AiChatStartBriefEvent, AiChatSubAgentCallBriefEvent, AiChatThinkBriefEvent, AiChatToolExecutionBriefEvent, AiChatUserQueryBriefEvent, UnknownAiChatBriefEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into AiChatBriefEvent with oneOf schemas: AiChatAwaitingInputBriefEvent, AiChatCompactorWarningBriefEvent, AiChatCompressorContextEndBriefEvent, AiChatCompressorContextStartBriefEvent, AiChatEndBriefEvent, AiChatErrorBriefEvent, AiChatManualInterruptBriefEvent, AiChatMessageBriefEvent, AiChatRequestBriefEvent, AiChatResponseBriefEvent, AiChatStartBriefEvent, AiChatSubAgentCallBriefEvent, AiChatThinkBriefEvent, AiChatToolExecutionBriefEvent, AiChatUserQueryBriefEvent, UnknownAiChatBriefEvent. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AiChatAwaitingInputBriefEvent, AiChatCompactorWarningBriefEvent, AiChatCompressorContextEndBriefEvent, AiChatCompressorContextStartBriefEvent, AiChatEndBriefEvent, AiChatErrorBriefEvent, AiChatManualInterruptBriefEvent, AiChatMessageBriefEvent, AiChatRequestBriefEvent, AiChatResponseBriefEvent, AiChatStartBriefEvent, AiChatSubAgentCallBriefEvent, AiChatThinkBriefEvent, AiChatToolExecutionBriefEvent, AiChatUserQueryBriefEvent, UnknownAiChatBriefEvent]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


