"""
Lingya Agents OpenAPI

本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.

The version of the OpenAPI document: 0.1.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from lingya_agents_sdk.models.ai_chat_file_ref import AiChatFileRef
from lingya_agents_sdk.models.chat_model_spec import ChatModelSpec


class AiChatInput(BaseModel):
    """
    AiChatInput 的公开协议结构。 / Public contract for ai chat input.
    """  # noqa: E501

    query: Annotated[str, Field(min_length=1, strict=True)] = Field(description="用户问题 / user query。")
    conversation_id: StrictStr | None = Field(
        default=None, description="会话 ID / conversation ID。", alias="conversationId"
    )
    chat_model_spec: ChatModelSpec | None = Field(
        default=None, description="字段 chatModelSpec / chat model spec field。", alias="chatModelSpec"
    )
    files: list[AiChatFileRef] | None = Field(default=None, description="字段 files / files field。")
    __properties: ClassVar[list[str]] = ["query", "conversationId", "chatModelSpec", "files"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of AiChatInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of chat_model_spec
        if self.chat_model_spec:
            _dict["chatModelSpec"] = self.chat_model_spec.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item_files in self.files:
                _items.append(_item_files.to_dict() if _item_files is not None else None)
            _dict["files"] = _items
        # set to None if conversation_id (nullable) is None
        # and model_fields_set contains the field
        if self.conversation_id is None and "conversation_id" in self.model_fields_set:
            _dict["conversationId"] = None

        # set to None if chat_model_spec (nullable) is None
        # and model_fields_set contains the field
        if self.chat_model_spec is None and "chat_model_spec" in self.model_fields_set:
            _dict["chatModelSpec"] = None

        # set to None if files (nullable) is None
        # and model_fields_set contains the field
        if self.files is None and "files" in self.model_fields_set:
            _dict["files"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of AiChatInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "query": obj.get("query"),
                "conversationId": obj.get("conversationId"),
                "chatModelSpec": ChatModelSpec.from_dict(obj["chatModelSpec"])
                if obj.get("chatModelSpec") is not None
                else None,
                "files": [AiChatFileRef.from_dict(_item) for _item in obj["files"]]
                if obj.get("files") is not None
                else None,
            }
        )
        return _obj
