# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from lingya_agents_sdk.models.assistant_chat_message import AssistantChatMessage
from lingya_agents_sdk.models.usage import Usage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AiChatResponseBriefEvent(BaseModel):
    """
    AiChatResponseBriefEvent 的公开协议结构。 / Public contract for ai chat response brief event.
    """ # noqa: E501
    type: StrictStr = Field(description="类型判别值 / type discriminator。")
    assistant_messages: List[AssistantChatMessage] = Field(description="字段 assistantMessages / assistant messages field。", alias="assistantMessages")
    usage: Usage = Field(description="字段 usage / usage field。")
    __properties: ClassVar[List[str]] = ["type", "assistantMessages", "usage"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['chat-client-response']):
            raise ValueError("must be one of enum values ('chat-client-response')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AiChatResponseBriefEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in assistant_messages (list)
        _items = []
        if self.assistant_messages:
            for _item_assistant_messages in self.assistant_messages:
                _items.append(_item_assistant_messages.to_dict() if _item_assistant_messages is not None else None)
            _dict['assistantMessages'] = _items
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AiChatResponseBriefEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "assistantMessages": [AssistantChatMessage.from_dict(_item) for _item in obj["assistantMessages"]] if obj.get("assistantMessages") is not None else None,
            "usage": Usage.from_dict(obj["usage"]) if obj.get("usage") is not None else None
        })
        return _obj


