# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ArtifactInfo(BaseModel):
    """
    ArtifactInfo 的公开协议结构。 / Public contract for artifact info.
    """ # noqa: E501
    file_id: StrictInt = Field(description="文件 ID / file ID。", alias="fileId")
    file_size: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 fileSize / file size field。", alias="fileSize")
    file_name: StrictStr = Field(description="文件名 / file name。", alias="fileName")
    mime_type: StrictStr = Field(description="MIME 类型 / MIME type。", alias="mimeType")
    relative_path: Optional[StrictStr] = Field(default=None, description="字段 relativePath / relative path field。", alias="relativePath")
    delivery_status: StrictStr = Field(description="字段 deliveryStatus / delivery status field。", alias="deliveryStatus")
    issue_codes: List[StrictStr] = Field(description="字段 issueCodes / issue codes field。", alias="issueCodes")
    recoverable: StrictBool = Field(description="字段 recoverable / recoverable field。")
    __properties: ClassVar[List[str]] = ["fileId", "fileSize", "fileName", "mimeType", "relativePath", "deliveryStatus", "issueCodes", "recoverable"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArtifactInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if relative_path (nullable) is None
        # and model_fields_set contains the field
        if self.relative_path is None and "relative_path" in self.model_fields_set:
            _dict['relativePath'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArtifactInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fileId": obj.get("fileId"),
            "fileSize": obj.get("fileSize"),
            "fileName": obj.get("fileName"),
            "mimeType": obj.get("mimeType"),
            "relativePath": obj.get("relativePath"),
            "deliveryStatus": obj.get("deliveryStatus"),
            "issueCodes": obj.get("issueCodes"),
            "recoverable": obj.get("recoverable")
        })
        return _obj


