# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AsyncTask(BaseModel):
    """
    AsyncTask 的公开协议结构。 / Public contract for async task.
    """ # noqa: E501
    task_id: StrictStr = Field(description="异步任务 ID / asynchronous task ID。", alias="taskId")
    task_type: StrictStr = Field(description="字段 taskType / task type field。", alias="taskType")
    title: StrictStr = Field(description="标题 / title。")
    status: StrictStr = Field(description="当前状态 / current status。")
    progress_percent: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="字段 progressPercent / progress percent field。", alias="progressPercent")
    phase: Optional[StrictStr] = Field(default=None, description="字段 phase / phase field。")
    status_message: Optional[StrictStr] = Field(default=None, description="字段 statusMessage / status message field。", alias="statusMessage")
    result_available: StrictBool = Field(description="字段 resultAvailable / result available field。", alias="resultAvailable")
    cancellable: StrictBool = Field(description="字段 cancellable / cancellable field。")
    failure_code: Optional[StrictStr] = Field(default=None, description="字段 failureCode / failure code field。", alias="failureCode")
    failure_message: Optional[StrictStr] = Field(default=None, description="字段 failureMessage / failure message field。", alias="failureMessage")
    origin_conversation_id: StrictStr = Field(description="字段 originConversationId / origin conversation id field。", alias="originConversationId")
    origin_message_id: StrictStr = Field(description="字段 originMessageId / origin message id field。", alias="originMessageId")
    origin_tool_id: StrictStr = Field(description="字段 originToolId / origin tool id field。", alias="originToolId")
    origin_tool_name: StrictStr = Field(description="字段 originToolName / origin tool name field。", alias="originToolName")
    target_message_id: StrictStr = Field(description="字段 targetMessageId / target message id field。", alias="targetMessageId")
    notification_status: StrictStr = Field(description="字段 notificationStatus / notification status field。", alias="notificationStatus")
    notification_message_id: Optional[StrictStr] = Field(default=None, description="字段 notificationMessageId / notification message id field。", alias="notificationMessageId")
    created_time: datetime = Field(description="创建时间 / creation time。", alias="createdTime")
    started_time: Optional[datetime] = Field(default=None, description="字段 startedTime / started time field。", alias="startedTime")
    completed_time: Optional[datetime] = Field(default=None, description="字段 completedTime / completed time field。", alias="completedTime")
    last_update_time: datetime = Field(description="最后更新时间 / last update time。", alias="lastUpdateTime")
    tracking_status: StrictStr = Field(description="字段 trackingStatus / tracking status field。", alias="trackingStatus")
    tracking_failure_code: Optional[StrictStr] = Field(default=None, description="字段 trackingFailureCode / tracking failure code field。", alias="trackingFailureCode")
    last_poll_error: Optional[StrictStr] = Field(default=None, description="字段 lastPollError / last poll error field。", alias="lastPollError")
    __properties: ClassVar[List[str]] = ["taskId", "taskType", "title", "status", "progressPercent", "phase", "statusMessage", "resultAvailable", "cancellable", "failureCode", "failureMessage", "originConversationId", "originMessageId", "originToolId", "originToolName", "targetMessageId", "notificationStatus", "notificationMessageId", "createdTime", "startedTime", "completedTime", "lastUpdateTime", "trackingStatus", "trackingFailureCode", "lastPollError"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AsyncTask from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if progress_percent (nullable) is None
        # and model_fields_set contains the field
        if self.progress_percent is None and "progress_percent" in self.model_fields_set:
            _dict['progressPercent'] = None

        # set to None if phase (nullable) is None
        # and model_fields_set contains the field
        if self.phase is None and "phase" in self.model_fields_set:
            _dict['phase'] = None

        # set to None if status_message (nullable) is None
        # and model_fields_set contains the field
        if self.status_message is None and "status_message" in self.model_fields_set:
            _dict['statusMessage'] = None

        # set to None if failure_code (nullable) is None
        # and model_fields_set contains the field
        if self.failure_code is None and "failure_code" in self.model_fields_set:
            _dict['failureCode'] = None

        # set to None if failure_message (nullable) is None
        # and model_fields_set contains the field
        if self.failure_message is None and "failure_message" in self.model_fields_set:
            _dict['failureMessage'] = None

        # set to None if notification_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.notification_message_id is None and "notification_message_id" in self.model_fields_set:
            _dict['notificationMessageId'] = None

        # set to None if started_time (nullable) is None
        # and model_fields_set contains the field
        if self.started_time is None and "started_time" in self.model_fields_set:
            _dict['startedTime'] = None

        # set to None if completed_time (nullable) is None
        # and model_fields_set contains the field
        if self.completed_time is None and "completed_time" in self.model_fields_set:
            _dict['completedTime'] = None

        # set to None if tracking_failure_code (nullable) is None
        # and model_fields_set contains the field
        if self.tracking_failure_code is None and "tracking_failure_code" in self.model_fields_set:
            _dict['trackingFailureCode'] = None

        # set to None if last_poll_error (nullable) is None
        # and model_fields_set contains the field
        if self.last_poll_error is None and "last_poll_error" in self.model_fields_set:
            _dict['lastPollError'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AsyncTask from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "taskId": obj.get("taskId"),
            "taskType": obj.get("taskType"),
            "title": obj.get("title"),
            "status": obj.get("status"),
            "progressPercent": obj.get("progressPercent"),
            "phase": obj.get("phase"),
            "statusMessage": obj.get("statusMessage"),
            "resultAvailable": obj.get("resultAvailable"),
            "cancellable": obj.get("cancellable"),
            "failureCode": obj.get("failureCode"),
            "failureMessage": obj.get("failureMessage"),
            "originConversationId": obj.get("originConversationId"),
            "originMessageId": obj.get("originMessageId"),
            "originToolId": obj.get("originToolId"),
            "originToolName": obj.get("originToolName"),
            "targetMessageId": obj.get("targetMessageId"),
            "notificationStatus": obj.get("notificationStatus"),
            "notificationMessageId": obj.get("notificationMessageId"),
            "createdTime": obj.get("createdTime"),
            "startedTime": obj.get("startedTime"),
            "completedTime": obj.get("completedTime"),
            "lastUpdateTime": obj.get("lastUpdateTime"),
            "trackingStatus": obj.get("trackingStatus"),
            "trackingFailureCode": obj.get("trackingFailureCode"),
            "lastPollError": obj.get("lastPollError")
        })
        return _obj


