# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from lingya_agents_sdk.models.boolean_chart_column import BooleanChartColumn
from lingya_agents_sdk.models.decimal_chart_column import DecimalChartColumn
from lingya_agents_sdk.models.double_chart_column import DoubleChartColumn
from lingya_agents_sdk.models.instant_chart_column import InstantChartColumn
from lingya_agents_sdk.models.integer_chart_column import IntegerChartColumn
from lingya_agents_sdk.models.local_date_chart_column import LocalDateChartColumn
from lingya_agents_sdk.models.local_date_time_chart_column import LocalDateTimeChartColumn
from lingya_agents_sdk.models.local_time_chart_column import LocalTimeChartColumn
from lingya_agents_sdk.models.string_chart_column import StringChartColumn
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

CHARTCOLUMNDATA_ONE_OF_SCHEMAS = ["BooleanChartColumn", "DecimalChartColumn", "DoubleChartColumn", "InstantChartColumn", "IntegerChartColumn", "LocalDateChartColumn", "LocalDateTimeChartColumn", "LocalTimeChartColumn", "StringChartColumn"]

class ChartColumnData(BaseModel):
    """
    ChartColumnData 的公开协议结构。 / Public contract for chart column data.
    """
    # data type: StringChartColumn
    oneof_schema_1_validator: Optional[StringChartColumn] = None
    # data type: IntegerChartColumn
    oneof_schema_2_validator: Optional[IntegerChartColumn] = None
    # data type: DecimalChartColumn
    oneof_schema_3_validator: Optional[DecimalChartColumn] = None
    # data type: DoubleChartColumn
    oneof_schema_4_validator: Optional[DoubleChartColumn] = None
    # data type: BooleanChartColumn
    oneof_schema_5_validator: Optional[BooleanChartColumn] = None
    # data type: LocalDateChartColumn
    oneof_schema_6_validator: Optional[LocalDateChartColumn] = None
    # data type: LocalDateTimeChartColumn
    oneof_schema_7_validator: Optional[LocalDateTimeChartColumn] = None
    # data type: LocalTimeChartColumn
    oneof_schema_8_validator: Optional[LocalTimeChartColumn] = None
    # data type: InstantChartColumn
    oneof_schema_9_validator: Optional[InstantChartColumn] = None
    actual_instance: Optional[Union[BooleanChartColumn, DecimalChartColumn, DoubleChartColumn, InstantChartColumn, IntegerChartColumn, LocalDateChartColumn, LocalDateTimeChartColumn, LocalTimeChartColumn, StringChartColumn]] = None
    one_of_schemas: Set[str] = { "BooleanChartColumn", "DecimalChartColumn", "DoubleChartColumn", "InstantChartColumn", "IntegerChartColumn", "LocalDateChartColumn", "LocalDateTimeChartColumn", "LocalTimeChartColumn", "StringChartColumn" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ChartColumnData.model_construct()
        error_messages = []
        match = 0
        # validate data type: StringChartColumn
        if not isinstance(v, StringChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `StringChartColumn`")
        else:
            match += 1
        # validate data type: IntegerChartColumn
        if not isinstance(v, IntegerChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IntegerChartColumn`")
        else:
            match += 1
        # validate data type: DecimalChartColumn
        if not isinstance(v, DecimalChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DecimalChartColumn`")
        else:
            match += 1
        # validate data type: DoubleChartColumn
        if not isinstance(v, DoubleChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DoubleChartColumn`")
        else:
            match += 1
        # validate data type: BooleanChartColumn
        if not isinstance(v, BooleanChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BooleanChartColumn`")
        else:
            match += 1
        # validate data type: LocalDateChartColumn
        if not isinstance(v, LocalDateChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LocalDateChartColumn`")
        else:
            match += 1
        # validate data type: LocalDateTimeChartColumn
        if not isinstance(v, LocalDateTimeChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LocalDateTimeChartColumn`")
        else:
            match += 1
        # validate data type: LocalTimeChartColumn
        if not isinstance(v, LocalTimeChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LocalTimeChartColumn`")
        else:
            match += 1
        # validate data type: InstantChartColumn
        if not isinstance(v, InstantChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InstantChartColumn`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ChartColumnData with oneOf schemas: BooleanChartColumn, DecimalChartColumn, DoubleChartColumn, InstantChartColumn, IntegerChartColumn, LocalDateChartColumn, LocalDateTimeChartColumn, LocalTimeChartColumn, StringChartColumn. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ChartColumnData with oneOf schemas: BooleanChartColumn, DecimalChartColumn, DoubleChartColumn, InstantChartColumn, IntegerChartColumn, LocalDateChartColumn, LocalDateTimeChartColumn, LocalTimeChartColumn, StringChartColumn. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into StringChartColumn
        try:
            instance.actual_instance = StringChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IntegerChartColumn
        try:
            instance.actual_instance = IntegerChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DecimalChartColumn
        try:
            instance.actual_instance = DecimalChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DoubleChartColumn
        try:
            instance.actual_instance = DoubleChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BooleanChartColumn
        try:
            instance.actual_instance = BooleanChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LocalDateChartColumn
        try:
            instance.actual_instance = LocalDateChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LocalDateTimeChartColumn
        try:
            instance.actual_instance = LocalDateTimeChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LocalTimeChartColumn
        try:
            instance.actual_instance = LocalTimeChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InstantChartColumn
        try:
            instance.actual_instance = InstantChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ChartColumnData with oneOf schemas: BooleanChartColumn, DecimalChartColumn, DoubleChartColumn, InstantChartColumn, IntegerChartColumn, LocalDateChartColumn, LocalDateTimeChartColumn, LocalTimeChartColumn, StringChartColumn. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ChartColumnData with oneOf schemas: BooleanChartColumn, DecimalChartColumn, DoubleChartColumn, InstantChartColumn, IntegerChartColumn, LocalDateChartColumn, LocalDateTimeChartColumn, LocalTimeChartColumn, StringChartColumn. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], BooleanChartColumn, DecimalChartColumn, DoubleChartColumn, InstantChartColumn, IntegerChartColumn, LocalDateChartColumn, LocalDateTimeChartColumn, LocalTimeChartColumn, StringChartColumn]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


