"""
Lingya Agents OpenAPI

本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.

The version of the OpenAPI document: 0.1.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from lingya_agents_sdk.models.chart_number_format import ChartNumberFormat


class ChartSeries(BaseModel):
    """
    ChartSeries 的公开协议结构。 / Public contract for chart series.
    """  # noqa: E501

    name: StrictStr = Field(description="字段 name / name field。")
    value_column: StrictStr = Field(description="字段 valueColumn / value column field。", alias="valueColumn")
    render_type: StrictStr = Field(description="字段 renderType / render type field。", alias="renderType")
    axis: StrictStr = Field(description="字段 axis / axis field。")
    number_format: ChartNumberFormat = Field(
        description="字段 numberFormat / number format field。", alias="numberFormat"
    )
    stack: StrictStr | None = Field(default=None, description="字段 stack / stack field。")
    __properties: ClassVar[list[str]] = ["name", "valueColumn", "renderType", "axis", "numberFormat", "stack"]

    @field_validator("render_type")
    def render_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["BAR", "LINE", "PIE"]):
            raise ValueError("must be one of enum values ('BAR', 'LINE', 'PIE')")
        return value

    @field_validator("axis")
    def axis_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["PRIMARY", "SECONDARY"]):
            raise ValueError("must be one of enum values ('PRIMARY', 'SECONDARY')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ChartSeries from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of number_format
        if self.number_format:
            _dict["numberFormat"] = self.number_format.to_dict()
        # set to None if stack (nullable) is None
        # and model_fields_set contains the field
        if self.stack is None and "stack" in self.model_fields_set:
            _dict["stack"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ChartSeries from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "valueColumn": obj.get("valueColumn"),
                "renderType": obj.get("renderType"),
                "axis": obj.get("axis"),
                "numberFormat": ChartNumberFormat.from_dict(obj["numberFormat"])
                if obj.get("numberFormat") is not None
                else None,
                "stack": obj.get("stack"),
            }
        )
        return _obj
