# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from lingya_agents_sdk.models.chart_series import ChartSeries
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ChartSpec(BaseModel):
    """
    ChartSpec 的公开协议结构。 / Public contract for chart spec.
    """ # noqa: E501
    version: StrictInt = Field(description="字段 version / version field。")
    type: StrictStr = Field(description="类型判别值 / type discriminator。")
    title: StrictStr = Field(description="标题 / title。")
    subtitle: Optional[StrictStr] = Field(default=None, description="字段 subtitle / subtitle field。")
    category_column: StrictStr = Field(description="字段 categoryColumn / category column field。", alias="categoryColumn")
    category_type: StrictStr = Field(description="字段 categoryType / category type field。", alias="categoryType")
    orientation: StrictStr = Field(description="字段 orientation / orientation field。")
    series: List[ChartSeries] = Field(description="字段 series / series field。")
    legend: StrictBool = Field(description="字段 legend / legend field。")
    data_zoom: StrictStr = Field(description="字段 dataZoom / data zoom field。", alias="dataZoom")
    null_policy: StrictStr = Field(description="字段 nullPolicy / null policy field。", alias="nullPolicy")
    __properties: ClassVar[List[str]] = ["version", "type", "title", "subtitle", "categoryColumn", "categoryType", "orientation", "series", "legend", "dataZoom", "nullPolicy"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['BAR', 'LINE', 'BAR_LINE', 'STACKED_BAR', 'PIE']):
            raise ValueError("must be one of enum values ('BAR', 'LINE', 'BAR_LINE', 'STACKED_BAR', 'PIE')")
        return value

    @field_validator('category_type')
    def category_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['CATEGORY', 'TIME']):
            raise ValueError("must be one of enum values ('CATEGORY', 'TIME')")
        return value

    @field_validator('orientation')
    def orientation_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['VERTICAL', 'HORIZONTAL']):
            raise ValueError("must be one of enum values ('VERTICAL', 'HORIZONTAL')")
        return value

    @field_validator('data_zoom')
    def data_zoom_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['NONE', 'AUTO']):
            raise ValueError("must be one of enum values ('NONE', 'AUTO')")
        return value

    @field_validator('null_policy')
    def null_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['GAP', 'ZERO', 'REJECT']):
            raise ValueError("must be one of enum values ('GAP', 'ZERO', 'REJECT')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChartSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in series (list)
        _items = []
        if self.series:
            for _item_series in self.series:
                _items.append(_item_series.to_dict() if _item_series is not None else None)
            _dict['series'] = _items
        # set to None if subtitle (nullable) is None
        # and model_fields_set contains the field
        if self.subtitle is None and "subtitle" in self.model_fields_set:
            _dict['subtitle'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChartSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "type": obj.get("type"),
            "title": obj.get("title"),
            "subtitle": obj.get("subtitle"),
            "categoryColumn": obj.get("categoryColumn"),
            "categoryType": obj.get("categoryType"),
            "orientation": obj.get("orientation"),
            "series": [ChartSeries.from_dict(_item) for _item in obj["series"]] if obj.get("series") is not None else None,
            "legend": obj.get("legend"),
            "dataZoom": obj.get("dataZoom"),
            "nullPolicy": obj.get("nullPolicy")
        })
        return _obj


