# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from lingya_agents_sdk.models.chart_number_format import ChartNumberFormat
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ChartSeries(BaseModel):
    """
    ChartSeries 的公开协议结构。 / Public contract for chart series.
    """ # noqa: E501
    name: StrictStr = Field(description="字段 name / name field。")
    value_column: StrictStr = Field(description="字段 valueColumn / value column field。", alias="valueColumn")
    render_type: StrictStr = Field(description="字段 renderType / render type field。", alias="renderType")
    axis: StrictStr = Field(description="字段 axis / axis field。")
    number_format: ChartNumberFormat = Field(description="字段 numberFormat / number format field。", alias="numberFormat")
    stack: Optional[StrictStr] = Field(default=None, description="字段 stack / stack field。")
    __properties: ClassVar[List[str]] = ["name", "valueColumn", "renderType", "axis", "numberFormat", "stack"]

    @field_validator('render_type')
    def render_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['BAR', 'LINE', 'PIE']):
            raise ValueError("must be one of enum values ('BAR', 'LINE', 'PIE')")
        return value

    @field_validator('axis')
    def axis_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PRIMARY', 'SECONDARY']):
            raise ValueError("must be one of enum values ('PRIMARY', 'SECONDARY')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChartSeries from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of number_format
        if self.number_format:
            _dict['numberFormat'] = self.number_format.to_dict()
        # set to None if stack (nullable) is None
        # and model_fields_set contains the field
        if self.stack is None and "stack" in self.model_fields_set:
            _dict['stack'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChartSeries from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "valueColumn": obj.get("valueColumn"),
            "renderType": obj.get("renderType"),
            "axis": obj.get("axis"),
            "numberFormat": ChartNumberFormat.from_dict(obj["numberFormat"]) if obj.get("numberFormat") is not None else None,
            "stack": obj.get("stack")
        })
        return _obj


