"""
Lingya Agents OpenAPI

本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.

The version of the OpenAPI document: 0.1.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, Union

from pydantic import BaseModel, ConfigDict, ValidationError, field_validator
from typing_extensions import Self

from lingya_agents_sdk.models.boolean_chart_column import BooleanChartColumn
from lingya_agents_sdk.models.decimal_chart_column import DecimalChartColumn
from lingya_agents_sdk.models.double_chart_column import DoubleChartColumn
from lingya_agents_sdk.models.instant_chart_column import InstantChartColumn
from lingya_agents_sdk.models.integer_chart_column import IntegerChartColumn
from lingya_agents_sdk.models.local_date_chart_column import LocalDateChartColumn
from lingya_agents_sdk.models.local_date_time_chart_column import LocalDateTimeChartColumn
from lingya_agents_sdk.models.local_time_chart_column import LocalTimeChartColumn
from lingya_agents_sdk.models.string_chart_column import StringChartColumn

CHARTCOLUMNDATA_ONE_OF_SCHEMAS = [
    "BooleanChartColumn",
    "DecimalChartColumn",
    "DoubleChartColumn",
    "InstantChartColumn",
    "IntegerChartColumn",
    "LocalDateChartColumn",
    "LocalDateTimeChartColumn",
    "LocalTimeChartColumn",
    "StringChartColumn",
]


class ChartColumnData(BaseModel):
    """
    ChartColumnData 的公开协议结构。 / Public contract for chart column data.
    """

    # data type: StringChartColumn
    oneof_schema_1_validator: StringChartColumn | None = None
    # data type: IntegerChartColumn
    oneof_schema_2_validator: IntegerChartColumn | None = None
    # data type: DecimalChartColumn
    oneof_schema_3_validator: DecimalChartColumn | None = None
    # data type: DoubleChartColumn
    oneof_schema_4_validator: DoubleChartColumn | None = None
    # data type: BooleanChartColumn
    oneof_schema_5_validator: BooleanChartColumn | None = None
    # data type: LocalDateChartColumn
    oneof_schema_6_validator: LocalDateChartColumn | None = None
    # data type: LocalDateTimeChartColumn
    oneof_schema_7_validator: LocalDateTimeChartColumn | None = None
    # data type: LocalTimeChartColumn
    oneof_schema_8_validator: LocalTimeChartColumn | None = None
    # data type: InstantChartColumn
    oneof_schema_9_validator: InstantChartColumn | None = None
    actual_instance: (
        Union[
            BooleanChartColumn,
            DecimalChartColumn,
            DoubleChartColumn,
            InstantChartColumn,
            IntegerChartColumn,
            LocalDateChartColumn,
            LocalDateTimeChartColumn,
            LocalTimeChartColumn,
            StringChartColumn,
        ]
        | None
    ) = None
    one_of_schemas: set[str] = {
        "BooleanChartColumn",
        "DecimalChartColumn",
        "DoubleChartColumn",
        "InstantChartColumn",
        "IntegerChartColumn",
        "LocalDateChartColumn",
        "LocalDateTimeChartColumn",
        "LocalTimeChartColumn",
        "StringChartColumn",
    }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    discriminator_value_class_map: dict[str, str] = {}

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        ChartColumnData.model_construct()
        error_messages = []
        match = 0
        # validate data type: StringChartColumn
        if not isinstance(v, StringChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `StringChartColumn`")
        else:
            match += 1
        # validate data type: IntegerChartColumn
        if not isinstance(v, IntegerChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IntegerChartColumn`")
        else:
            match += 1
        # validate data type: DecimalChartColumn
        if not isinstance(v, DecimalChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DecimalChartColumn`")
        else:
            match += 1
        # validate data type: DoubleChartColumn
        if not isinstance(v, DoubleChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DoubleChartColumn`")
        else:
            match += 1
        # validate data type: BooleanChartColumn
        if not isinstance(v, BooleanChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BooleanChartColumn`")
        else:
            match += 1
        # validate data type: LocalDateChartColumn
        if not isinstance(v, LocalDateChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LocalDateChartColumn`")
        else:
            match += 1
        # validate data type: LocalDateTimeChartColumn
        if not isinstance(v, LocalDateTimeChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LocalDateTimeChartColumn`")
        else:
            match += 1
        # validate data type: LocalTimeChartColumn
        if not isinstance(v, LocalTimeChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LocalTimeChartColumn`")
        else:
            match += 1
        # validate data type: InstantChartColumn
        if not isinstance(v, InstantChartColumn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InstantChartColumn`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in ChartColumnData with oneOf schemas: BooleanChartColumn, DecimalChartColumn, DoubleChartColumn, InstantChartColumn, IntegerChartColumn, LocalDateChartColumn, LocalDateTimeChartColumn, LocalTimeChartColumn, StringChartColumn. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in ChartColumnData with oneOf schemas: BooleanChartColumn, DecimalChartColumn, DoubleChartColumn, InstantChartColumn, IntegerChartColumn, LocalDateChartColumn, LocalDateTimeChartColumn, LocalTimeChartColumn, StringChartColumn. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into StringChartColumn
        try:
            instance.actual_instance = StringChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IntegerChartColumn
        try:
            instance.actual_instance = IntegerChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DecimalChartColumn
        try:
            instance.actual_instance = DecimalChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DoubleChartColumn
        try:
            instance.actual_instance = DoubleChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BooleanChartColumn
        try:
            instance.actual_instance = BooleanChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LocalDateChartColumn
        try:
            instance.actual_instance = LocalDateChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LocalDateTimeChartColumn
        try:
            instance.actual_instance = LocalDateTimeChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LocalTimeChartColumn
        try:
            instance.actual_instance = LocalTimeChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InstantChartColumn
        try:
            instance.actual_instance = InstantChartColumn.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into ChartColumnData with oneOf schemas: BooleanChartColumn, DecimalChartColumn, DoubleChartColumn, InstantChartColumn, IntegerChartColumn, LocalDateChartColumn, LocalDateTimeChartColumn, LocalTimeChartColumn, StringChartColumn. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into ChartColumnData with oneOf schemas: BooleanChartColumn, DecimalChartColumn, DoubleChartColumn, InstantChartColumn, IntegerChartColumn, LocalDateChartColumn, LocalDateTimeChartColumn, LocalTimeChartColumn, StringChartColumn. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> (
        Union[
            dict[str, Any],
            BooleanChartColumn,
            DecimalChartColumn,
            DoubleChartColumn,
            InstantChartColumn,
            IntegerChartColumn,
            LocalDateChartColumn,
            LocalDateTimeChartColumn,
            LocalTimeChartColumn,
            StringChartColumn,
        ]
        | None
    ):
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
