"""
Lingya Agents OpenAPI

本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.

The version of the OpenAPI document: 0.1.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar, Union

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self


class ChatModelSpec(BaseModel):
    """
    ChatModelSpec 的公开协议结构。 / Public contract for chat model spec.
    """  # noqa: E501

    key_group_id: Annotated[int, Field(strict=True, ge=1)] = Field(
        description="字段 keyGroupId / key group id field。", alias="keyGroupId"
    )
    model: Annotated[str, Field(min_length=1, strict=True)] = Field(description="字段 model / model field。")
    thinking: StrictBool | None = Field(default=None, description="字段 thinking / thinking field。")
    stop_sequences: list[StrictStr] | None = Field(
        default=None, description="字段 stopSequences / stop sequences field。", alias="stopSequences"
    )
    temperature: (
        Union[Annotated[float, Field(le=2, strict=True, ge=0)], Annotated[int, Field(le=2, strict=True, ge=0)]] | None
    ) = Field(default=None, description="字段 temperature / temperature field。")
    max_tokens: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=None, description="字段 maxTokens / max tokens field。", alias="maxTokens"
    )
    top_p: (
        Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]] | None
    ) = Field(default=None, description="字段 topP / top p field。", alias="topP")
    top_k: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=None, description="字段 topK / top k field。", alias="topK"
    )
    frequency_penalty: (
        Union[Annotated[float, Field(le=2, strict=True, ge=-2)], Annotated[int, Field(le=2, strict=True, ge=-2)]] | None
    ) = Field(default=None, description="字段 frequencyPenalty / frequency penalty field。", alias="frequencyPenalty")
    presence_penalty: (
        Union[Annotated[float, Field(le=2, strict=True, ge=-2)], Annotated[int, Field(le=2, strict=True, ge=-2)]] | None
    ) = Field(default=None, description="字段 presencePenalty / presence penalty field。", alias="presencePenalty")
    __properties: ClassVar[list[str]] = [
        "keyGroupId",
        "model",
        "thinking",
        "stopSequences",
        "temperature",
        "maxTokens",
        "topP",
        "topK",
        "frequencyPenalty",
        "presencePenalty",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ChatModelSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if thinking (nullable) is None
        # and model_fields_set contains the field
        if self.thinking is None and "thinking" in self.model_fields_set:
            _dict["thinking"] = None

        # set to None if stop_sequences (nullable) is None
        # and model_fields_set contains the field
        if self.stop_sequences is None and "stop_sequences" in self.model_fields_set:
            _dict["stopSequences"] = None

        # set to None if temperature (nullable) is None
        # and model_fields_set contains the field
        if self.temperature is None and "temperature" in self.model_fields_set:
            _dict["temperature"] = None

        # set to None if max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.max_tokens is None and "max_tokens" in self.model_fields_set:
            _dict["maxTokens"] = None

        # set to None if top_p (nullable) is None
        # and model_fields_set contains the field
        if self.top_p is None and "top_p" in self.model_fields_set:
            _dict["topP"] = None

        # set to None if top_k (nullable) is None
        # and model_fields_set contains the field
        if self.top_k is None and "top_k" in self.model_fields_set:
            _dict["topK"] = None

        # set to None if frequency_penalty (nullable) is None
        # and model_fields_set contains the field
        if self.frequency_penalty is None and "frequency_penalty" in self.model_fields_set:
            _dict["frequencyPenalty"] = None

        # set to None if presence_penalty (nullable) is None
        # and model_fields_set contains the field
        if self.presence_penalty is None and "presence_penalty" in self.model_fields_set:
            _dict["presencePenalty"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ChatModelSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "keyGroupId": obj.get("keyGroupId"),
                "model": obj.get("model"),
                "thinking": obj.get("thinking"),
                "stopSequences": obj.get("stopSequences"),
                "temperature": obj.get("temperature"),
                "maxTokens": obj.get("maxTokens"),
                "topP": obj.get("topP"),
                "topK": obj.get("topK"),
                "frequencyPenalty": obj.get("frequencyPenalty"),
                "presencePenalty": obj.get("presencePenalty"),
            }
        )
        return _obj
