# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ChatModelConfig(BaseModel):
    """
    ChatModelConfig 的公开协议结构。 / Public contract for chat model config.
    """ # noqa: E501
    maker: StrictStr = Field(description="字段 maker / maker field。")
    model_name: StrictStr = Field(description="字段 modelName / model name field。", alias="modelName")
    model_label: StrictStr = Field(description="字段 modelLabel / model label field。", alias="modelLabel")
    model_description: StrictStr = Field(description="字段 modelDescription / model description field。", alias="modelDescription")
    max_context_tokens: StrictInt = Field(description="字段 maxContextTokens / max context tokens field。", alias="maxContextTokens")
    max_output_tokens: StrictInt = Field(description="字段 maxOutputTokens / max output tokens field。", alias="maxOutputTokens")
    support_image: StrictBool = Field(description="字段 supportImage / support image field。", alias="supportImage")
    support_video: StrictBool = Field(description="字段 supportVideo / support video field。", alias="supportVideo")
    thinking_mode: StrictBool = Field(description="字段 thinkingMode / thinking mode field。", alias="thinkingMode")
    __properties: ClassVar[List[str]] = ["maker", "modelName", "modelLabel", "modelDescription", "maxContextTokens", "maxOutputTokens", "supportImage", "supportVideo", "thinkingMode"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChatModelConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChatModelConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "maker": obj.get("maker"),
            "modelName": obj.get("modelName"),
            "modelLabel": obj.get("modelLabel"),
            "modelDescription": obj.get("modelDescription"),
            "maxContextTokens": obj.get("maxContextTokens"),
            "maxOutputTokens": obj.get("maxOutputTokens"),
            "supportImage": obj.get("supportImage"),
            "supportVideo": obj.get("supportVideo"),
            "thinkingMode": obj.get("thinkingMode")
        })
        return _obj


