"""
Lingya Agents OpenAPI

本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.

The version of the OpenAPI document: 0.1.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, Union

from pydantic import BaseModel, ConfigDict, ValidationError, field_validator
from typing_extensions import Self

from lingya_agents_sdk.models.assistant_chat_message import AssistantChatMessage
from lingya_agents_sdk.models.system_chat_message import SystemChatMessage
from lingya_agents_sdk.models.tool_response_chat_message import ToolResponseChatMessage
from lingya_agents_sdk.models.user_chat_message import UserChatMessage

CHATMESSAGE_ONE_OF_SCHEMAS = ["AssistantChatMessage", "SystemChatMessage", "ToolResponseChatMessage", "UserChatMessage"]


class ChatMessage(BaseModel):
    """
    ChatMessage 的公开协议结构。 / Public contract for chat message.
    """

    # data type: SystemChatMessage
    oneof_schema_1_validator: SystemChatMessage | None = None
    # data type: UserChatMessage
    oneof_schema_2_validator: UserChatMessage | None = None
    # data type: AssistantChatMessage
    oneof_schema_3_validator: AssistantChatMessage | None = None
    # data type: ToolResponseChatMessage
    oneof_schema_4_validator: ToolResponseChatMessage | None = None
    actual_instance: Union[AssistantChatMessage, SystemChatMessage, ToolResponseChatMessage, UserChatMessage] | None = (
        None
    )
    one_of_schemas: set[str] = {
        "AssistantChatMessage",
        "SystemChatMessage",
        "ToolResponseChatMessage",
        "UserChatMessage",
    }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    discriminator_value_class_map: dict[str, str] = {}

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        ChatMessage.model_construct()
        error_messages = []
        match = 0
        # validate data type: SystemChatMessage
        if not isinstance(v, SystemChatMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SystemChatMessage`")
        else:
            match += 1
        # validate data type: UserChatMessage
        if not isinstance(v, UserChatMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserChatMessage`")
        else:
            match += 1
        # validate data type: AssistantChatMessage
        if not isinstance(v, AssistantChatMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AssistantChatMessage`")
        else:
            match += 1
        # validate data type: ToolResponseChatMessage
        if not isinstance(v, ToolResponseChatMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ToolResponseChatMessage`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in ChatMessage with oneOf schemas: AssistantChatMessage, SystemChatMessage, ToolResponseChatMessage, UserChatMessage. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in ChatMessage with oneOf schemas: AssistantChatMessage, SystemChatMessage, ToolResponseChatMessage, UserChatMessage. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into SystemChatMessage
        try:
            instance.actual_instance = SystemChatMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserChatMessage
        try:
            instance.actual_instance = UserChatMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AssistantChatMessage
        try:
            instance.actual_instance = AssistantChatMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ToolResponseChatMessage
        try:
            instance.actual_instance = ToolResponseChatMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into ChatMessage with oneOf schemas: AssistantChatMessage, SystemChatMessage, ToolResponseChatMessage, UserChatMessage. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into ChatMessage with oneOf schemas: AssistantChatMessage, SystemChatMessage, ToolResponseChatMessage, UserChatMessage. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> (
        Union[dict[str, Any], AssistantChatMessage, SystemChatMessage, ToolResponseChatMessage, UserChatMessage] | None
    ):
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
