# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from lingya_agents_sdk.models.assistant_chat_message import AssistantChatMessage
from lingya_agents_sdk.models.system_chat_message import SystemChatMessage
from lingya_agents_sdk.models.tool_response_chat_message import ToolResponseChatMessage
from lingya_agents_sdk.models.user_chat_message import UserChatMessage
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

CHATMESSAGE_ONE_OF_SCHEMAS = ["AssistantChatMessage", "SystemChatMessage", "ToolResponseChatMessage", "UserChatMessage"]

class ChatMessage(BaseModel):
    """
    ChatMessage 的公开协议结构。 / Public contract for chat message.
    """
    # data type: SystemChatMessage
    oneof_schema_1_validator: Optional[SystemChatMessage] = None
    # data type: UserChatMessage
    oneof_schema_2_validator: Optional[UserChatMessage] = None
    # data type: AssistantChatMessage
    oneof_schema_3_validator: Optional[AssistantChatMessage] = None
    # data type: ToolResponseChatMessage
    oneof_schema_4_validator: Optional[ToolResponseChatMessage] = None
    actual_instance: Optional[Union[AssistantChatMessage, SystemChatMessage, ToolResponseChatMessage, UserChatMessage]] = None
    one_of_schemas: Set[str] = { "AssistantChatMessage", "SystemChatMessage", "ToolResponseChatMessage", "UserChatMessage" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ChatMessage.model_construct()
        error_messages = []
        match = 0
        # validate data type: SystemChatMessage
        if not isinstance(v, SystemChatMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SystemChatMessage`")
        else:
            match += 1
        # validate data type: UserChatMessage
        if not isinstance(v, UserChatMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserChatMessage`")
        else:
            match += 1
        # validate data type: AssistantChatMessage
        if not isinstance(v, AssistantChatMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AssistantChatMessage`")
        else:
            match += 1
        # validate data type: ToolResponseChatMessage
        if not isinstance(v, ToolResponseChatMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ToolResponseChatMessage`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ChatMessage with oneOf schemas: AssistantChatMessage, SystemChatMessage, ToolResponseChatMessage, UserChatMessage. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ChatMessage with oneOf schemas: AssistantChatMessage, SystemChatMessage, ToolResponseChatMessage, UserChatMessage. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into SystemChatMessage
        try:
            instance.actual_instance = SystemChatMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserChatMessage
        try:
            instance.actual_instance = UserChatMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AssistantChatMessage
        try:
            instance.actual_instance = AssistantChatMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ToolResponseChatMessage
        try:
            instance.actual_instance = ToolResponseChatMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ChatMessage with oneOf schemas: AssistantChatMessage, SystemChatMessage, ToolResponseChatMessage, UserChatMessage. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ChatMessage with oneOf schemas: AssistantChatMessage, SystemChatMessage, ToolResponseChatMessage, UserChatMessage. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AssistantChatMessage, SystemChatMessage, ToolResponseChatMessage, UserChatMessage]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


