# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ChatOptions(BaseModel):
    """
    ChatOptions 的公开协议结构。 / Public contract for chat options.
    """ # noqa: E501
    model: Optional[StrictStr] = Field(default=None, description="字段 model / model field。")
    frequency_penalty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="字段 frequencyPenalty / frequency penalty field。", alias="frequencyPenalty")
    max_tokens: Optional[StrictInt] = Field(default=None, description="字段 maxTokens / max tokens field。", alias="maxTokens")
    presence_penalty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="字段 presencePenalty / presence penalty field。", alias="presencePenalty")
    stop_sequences: Optional[List[StrictStr]] = Field(default=None, description="字段 stopSequences / stop sequences field。", alias="stopSequences")
    temperature: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="字段 temperature / temperature field。")
    top_p: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="字段 topP / top p field。", alias="topP")
    __properties: ClassVar[List[str]] = ["model", "frequencyPenalty", "maxTokens", "presencePenalty", "stopSequences", "temperature", "topP"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChatOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        # set to None if frequency_penalty (nullable) is None
        # and model_fields_set contains the field
        if self.frequency_penalty is None and "frequency_penalty" in self.model_fields_set:
            _dict['frequencyPenalty'] = None

        # set to None if max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.max_tokens is None and "max_tokens" in self.model_fields_set:
            _dict['maxTokens'] = None

        # set to None if presence_penalty (nullable) is None
        # and model_fields_set contains the field
        if self.presence_penalty is None and "presence_penalty" in self.model_fields_set:
            _dict['presencePenalty'] = None

        # set to None if stop_sequences (nullable) is None
        # and model_fields_set contains the field
        if self.stop_sequences is None and "stop_sequences" in self.model_fields_set:
            _dict['stopSequences'] = None

        # set to None if temperature (nullable) is None
        # and model_fields_set contains the field
        if self.temperature is None and "temperature" in self.model_fields_set:
            _dict['temperature'] = None

        # set to None if top_p (nullable) is None
        # and model_fields_set contains the field
        if self.top_p is None and "top_p" in self.model_fields_set:
            _dict['topP'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChatOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "model": obj.get("model"),
            "frequencyPenalty": obj.get("frequencyPenalty"),
            "maxTokens": obj.get("maxTokens"),
            "presencePenalty": obj.get("presencePenalty"),
            "stopSequences": obj.get("stopSequences"),
            "temperature": obj.get("temperature"),
            "topP": obj.get("topP")
        })
        return _obj


