# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from lingya_agents_sdk.models.usage import Usage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConversationSummary(BaseModel):
    """
    ConversationSummary 的公开协议结构。 / Public contract for conversation summary.
    """ # noqa: E501
    conversation_id: StrictStr = Field(description="会话 ID / conversation ID。", alias="conversationId")
    conversation_type: StrictStr = Field(description="字段 conversationType / conversation type field。", alias="conversationType")
    title: Optional[StrictStr] = Field(default=None, description="标题 / title。")
    title_state: StrictStr = Field(description="字段 titleState / title state field。", alias="titleState")
    status: StrictStr = Field(description="当前状态 / current status。")
    message_count: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 messageCount / message count field。", alias="messageCount")
    total_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="总 Token 数 / total token count。", alias="totalTokens")
    total_input_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 totalInputTokens / total input tokens field。", alias="totalInputTokens")
    total_output_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 totalOutputTokens / total output tokens field。", alias="totalOutputTokens")
    usage: Usage = Field(description="字段 usage / usage field。")
    created_time: datetime = Field(description="创建时间 / creation time。", alias="createdTime")
    last_update_time: datetime = Field(description="最后更新时间 / last update time。", alias="lastUpdateTime")
    __properties: ClassVar[List[str]] = ["conversationId", "conversationType", "title", "titleState", "status", "messageCount", "totalTokens", "totalInputTokens", "totalOutputTokens", "usage", "createdTime", "lastUpdateTime"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConversationSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConversationSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conversationId": obj.get("conversationId"),
            "conversationType": obj.get("conversationType"),
            "title": obj.get("title"),
            "titleState": obj.get("titleState"),
            "status": obj.get("status"),
            "messageCount": obj.get("messageCount"),
            "totalTokens": obj.get("totalTokens"),
            "totalInputTokens": obj.get("totalInputTokens"),
            "totalOutputTokens": obj.get("totalOutputTokens"),
            "usage": Usage.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
            "createdTime": obj.get("createdTime"),
            "lastUpdateTime": obj.get("lastUpdateTime")
        })
        return _obj


