# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConversationActivity(BaseModel):
    """
    ConversationActivity 的公开协议结构。 / Public contract for conversation activity.
    """ # noqa: E501
    conversation_id: StrictStr = Field(description="会话 ID / conversation ID。", alias="conversationId")
    execution_status: StrictStr = Field(description="字段 executionStatus / execution status field。", alias="executionStatus")
    active_message_id: Optional[StrictStr] = Field(default=None, description="字段 activeMessageId / active message id field。", alias="activeMessageId")
    execution_epoch: Optional[StrictStr] = Field(default=None, description="字段 executionEpoch / execution epoch field。", alias="executionEpoch")
    execution_started_time: Optional[datetime] = Field(default=None, description="字段 executionStartedTime / execution started time field。", alias="executionStartedTime")
    latest_terminal_message_id: Optional[StrictStr] = Field(default=None, description="字段 latestTerminalMessageId / latest terminal message id field。", alias="latestTerminalMessageId")
    latest_terminal_time: Optional[datetime] = Field(default=None, description="字段 latestTerminalTime / latest terminal time field。", alias="latestTerminalTime")
    has_unread_completion: StrictBool = Field(description="字段 hasUnreadCompletion / has unread completion field。", alias="hasUnreadCompletion")
    requires_user_confirmation: StrictBool = Field(description="字段 requiresUserConfirmation / requires user confirmation field。", alias="requiresUserConfirmation")
    __properties: ClassVar[List[str]] = ["conversationId", "executionStatus", "activeMessageId", "executionEpoch", "executionStartedTime", "latestTerminalMessageId", "latestTerminalTime", "hasUnreadCompletion", "requiresUserConfirmation"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConversationActivity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if active_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.active_message_id is None and "active_message_id" in self.model_fields_set:
            _dict['activeMessageId'] = None

        # set to None if execution_epoch (nullable) is None
        # and model_fields_set contains the field
        if self.execution_epoch is None and "execution_epoch" in self.model_fields_set:
            _dict['executionEpoch'] = None

        # set to None if execution_started_time (nullable) is None
        # and model_fields_set contains the field
        if self.execution_started_time is None and "execution_started_time" in self.model_fields_set:
            _dict['executionStartedTime'] = None

        # set to None if latest_terminal_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.latest_terminal_message_id is None and "latest_terminal_message_id" in self.model_fields_set:
            _dict['latestTerminalMessageId'] = None

        # set to None if latest_terminal_time (nullable) is None
        # and model_fields_set contains the field
        if self.latest_terminal_time is None and "latest_terminal_time" in self.model_fields_set:
            _dict['latestTerminalTime'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConversationActivity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conversationId": obj.get("conversationId"),
            "executionStatus": obj.get("executionStatus"),
            "activeMessageId": obj.get("activeMessageId"),
            "executionEpoch": obj.get("executionEpoch"),
            "executionStartedTime": obj.get("executionStartedTime"),
            "latestTerminalMessageId": obj.get("latestTerminalMessageId"),
            "latestTerminalTime": obj.get("latestTerminalTime"),
            "hasUnreadCompletion": obj.get("hasUnreadCompletion"),
            "requiresUserConfirmation": obj.get("requiresUserConfirmation")
        })
        return _obj


