"""
Lingya Agents OpenAPI

本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.

The version of the OpenAPI document: 0.1.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from lingya_agents_sdk.models.usage import Usage


class ConversationSummary(BaseModel):
    """
    ConversationSummary 的公开协议结构。 / Public contract for conversation summary.
    """  # noqa: E501

    conversation_id: StrictStr = Field(description="会话 ID / conversation ID。", alias="conversationId")
    conversation_type: StrictStr = Field(
        description="字段 conversationType / conversation type field。", alias="conversationType"
    )
    title: StrictStr | None = Field(default=None, description="标题 / title。")
    title_state: StrictStr = Field(description="字段 titleState / title state field。", alias="titleState")
    status: StrictStr = Field(description="当前状态 / current status。")
    message_count: Annotated[int, Field(strict=True, ge=0)] = Field(
        description="字段 messageCount / message count field。", alias="messageCount"
    )
    total_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(
        description="总 Token 数 / total token count。", alias="totalTokens"
    )
    total_input_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(
        description="字段 totalInputTokens / total input tokens field。", alias="totalInputTokens"
    )
    total_output_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(
        description="字段 totalOutputTokens / total output tokens field。", alias="totalOutputTokens"
    )
    usage: Usage = Field(description="字段 usage / usage field。")
    created_time: datetime = Field(description="创建时间 / creation time。", alias="createdTime")
    last_update_time: datetime = Field(description="最后更新时间 / last update time。", alias="lastUpdateTime")
    __properties: ClassVar[list[str]] = [
        "conversationId",
        "conversationType",
        "title",
        "titleState",
        "status",
        "messageCount",
        "totalTokens",
        "totalInputTokens",
        "totalOutputTokens",
        "usage",
        "createdTime",
        "lastUpdateTime",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ConversationSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict["usage"] = self.usage.to_dict()
        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict["title"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ConversationSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "conversationId": obj.get("conversationId"),
                "conversationType": obj.get("conversationType"),
                "title": obj.get("title"),
                "titleState": obj.get("titleState"),
                "status": obj.get("status"),
                "messageCount": obj.get("messageCount"),
                "totalTokens": obj.get("totalTokens"),
                "totalInputTokens": obj.get("totalInputTokens"),
                "totalOutputTokens": obj.get("totalOutputTokens"),
                "usage": Usage.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
                "createdTime": obj.get("createdTime"),
                "lastUpdateTime": obj.get("lastUpdateTime"),
            }
        )
        return _obj
