# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from lingya_agents_sdk.models.conversation_user_message import ConversationUserMessage
from lingya_agents_sdk.models.usage import Usage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConversationMessage(BaseModel):
    """
    ConversationMessage 的公开协议结构。 / Public contract for conversation message.
    """ # noqa: E501
    message_id: StrictStr = Field(description="消息 ID / message ID。", alias="messageId")
    user_message: ConversationUserMessage = Field(description="字段 userMessage / user message field。", alias="userMessage")
    input_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="输入 Token 数 / input token count。", alias="inputTokens")
    output_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="输出 Token 数 / output token count。", alias="outputTokens")
    total_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="总 Token 数 / total token count。", alias="totalTokens")
    usage: Usage = Field(description="字段 usage / usage field。")
    execution_time_millis: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 executionTimeMillis / execution time millis field。", alias="executionTimeMillis")
    processing_steps: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 processingSteps / processing steps field。", alias="processingSteps")
    total_tool_calls: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 totalToolCalls / total tool calls field。", alias="totalToolCalls")
    status: StrictStr = Field(description="当前状态 / current status。")
    created_time: datetime = Field(description="创建时间 / creation time。", alias="createdTime")
    last_update_time: datetime = Field(description="最后更新时间 / last update time。", alias="lastUpdateTime")
    execution_type: StrictStr = Field(description="字段 executionType / execution type field。", alias="executionType")
    parent_message_id: Optional[StrictStr] = Field(default=None, description="字段 parentMessageId / parent message id field。", alias="parentMessageId")
    __properties: ClassVar[List[str]] = ["messageId", "userMessage", "inputTokens", "outputTokens", "totalTokens", "usage", "executionTimeMillis", "processingSteps", "totalToolCalls", "status", "createdTime", "lastUpdateTime", "executionType", "parentMessageId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConversationMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user_message
        if self.user_message:
            _dict['userMessage'] = self.user_message.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # set to None if parent_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_message_id is None and "parent_message_id" in self.model_fields_set:
            _dict['parentMessageId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConversationMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "messageId": obj.get("messageId"),
            "userMessage": ConversationUserMessage.from_dict(obj["userMessage"]) if obj.get("userMessage") is not None else None,
            "inputTokens": obj.get("inputTokens"),
            "outputTokens": obj.get("outputTokens"),
            "totalTokens": obj.get("totalTokens"),
            "usage": Usage.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
            "executionTimeMillis": obj.get("executionTimeMillis"),
            "processingSteps": obj.get("processingSteps"),
            "totalToolCalls": obj.get("totalToolCalls"),
            "status": obj.get("status"),
            "createdTime": obj.get("createdTime"),
            "lastUpdateTime": obj.get("lastUpdateTime"),
            "executionType": obj.get("executionType"),
            "parentMessageId": obj.get("parentMessageId")
        })
        return _obj


