# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConversationContextUsage(BaseModel):
    """
    ConversationContextUsage 的公开协议结构。 / Public contract for conversation context usage.
    """ # noqa: E501
    system_prompt_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 systemPromptTokens / system prompt tokens field。", alias="systemPromptTokens")
    session_message_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 sessionMessageTokens / session message tokens field。", alias="sessionMessageTokens")
    max_context_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 maxContextTokens / max context tokens field。", alias="maxContextTokens")
    tool_definition_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 toolDefinitionTokens / tool definition tokens field。", alias="toolDefinitionTokens")
    protocol_reserve_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 protocolReserveTokens / protocol reserve tokens field。", alias="protocolReserveTokens")
    active_context_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 activeContextTokens / active context tokens field。", alias="activeContextTokens")
    requested_output_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 requestedOutputTokens / requested output tokens field。", alias="requestedOutputTokens")
    message_assembly_reserve_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 messageAssemblyReserveTokens / message assembly reserve tokens field。", alias="messageAssemblyReserveTokens")
    required_context_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="字段 requiredContextTokens / required context tokens field。", alias="requiredContextTokens")
    active_usage_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="字段 activeUsageRatio / active usage ratio field。", alias="activeUsageRatio")
    required_usage_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="字段 requiredUsageRatio / required usage ratio field。", alias="requiredUsageRatio")
    calculation_source: StrictStr = Field(description="字段 calculationSource / calculation source field。", alias="calculationSource")
    __properties: ClassVar[List[str]] = ["systemPromptTokens", "sessionMessageTokens", "maxContextTokens", "toolDefinitionTokens", "protocolReserveTokens", "activeContextTokens", "requestedOutputTokens", "messageAssemblyReserveTokens", "requiredContextTokens", "activeUsageRatio", "requiredUsageRatio", "calculationSource"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConversationContextUsage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if active_usage_ratio (nullable) is None
        # and model_fields_set contains the field
        if self.active_usage_ratio is None and "active_usage_ratio" in self.model_fields_set:
            _dict['activeUsageRatio'] = None

        # set to None if required_usage_ratio (nullable) is None
        # and model_fields_set contains the field
        if self.required_usage_ratio is None and "required_usage_ratio" in self.model_fields_set:
            _dict['requiredUsageRatio'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConversationContextUsage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "systemPromptTokens": obj.get("systemPromptTokens"),
            "sessionMessageTokens": obj.get("sessionMessageTokens"),
            "maxContextTokens": obj.get("maxContextTokens"),
            "toolDefinitionTokens": obj.get("toolDefinitionTokens"),
            "protocolReserveTokens": obj.get("protocolReserveTokens"),
            "activeContextTokens": obj.get("activeContextTokens"),
            "requestedOutputTokens": obj.get("requestedOutputTokens"),
            "messageAssemblyReserveTokens": obj.get("messageAssemblyReserveTokens"),
            "requiredContextTokens": obj.get("requiredContextTokens"),
            "activeUsageRatio": obj.get("activeUsageRatio"),
            "requiredUsageRatio": obj.get("requiredUsageRatio"),
            "calculationSource": obj.get("calculationSource")
        })
        return _obj


