"""
Lingya Agents OpenAPI

本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.

The version of the OpenAPI document: 0.1.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self


class ConversationActivity(BaseModel):
    """
    ConversationActivity 的公开协议结构。 / Public contract for conversation activity.
    """  # noqa: E501

    conversation_id: StrictStr = Field(description="会话 ID / conversation ID。", alias="conversationId")
    execution_status: StrictStr = Field(
        description="字段 executionStatus / execution status field。", alias="executionStatus"
    )
    active_message_id: StrictStr | None = Field(
        default=None, description="字段 activeMessageId / active message id field。", alias="activeMessageId"
    )
    execution_epoch: StrictStr | None = Field(
        default=None, description="字段 executionEpoch / execution epoch field。", alias="executionEpoch"
    )
    execution_started_time: datetime | None = Field(
        default=None,
        description="字段 executionStartedTime / execution started time field。",
        alias="executionStartedTime",
    )
    latest_terminal_message_id: StrictStr | None = Field(
        default=None,
        description="字段 latestTerminalMessageId / latest terminal message id field。",
        alias="latestTerminalMessageId",
    )
    latest_terminal_time: datetime | None = Field(
        default=None, description="字段 latestTerminalTime / latest terminal time field。", alias="latestTerminalTime"
    )
    has_unread_completion: StrictBool = Field(
        description="字段 hasUnreadCompletion / has unread completion field。", alias="hasUnreadCompletion"
    )
    requires_user_confirmation: StrictBool = Field(
        description="字段 requiresUserConfirmation / requires user confirmation field。",
        alias="requiresUserConfirmation",
    )
    __properties: ClassVar[list[str]] = [
        "conversationId",
        "executionStatus",
        "activeMessageId",
        "executionEpoch",
        "executionStartedTime",
        "latestTerminalMessageId",
        "latestTerminalTime",
        "hasUnreadCompletion",
        "requiresUserConfirmation",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ConversationActivity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if active_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.active_message_id is None and "active_message_id" in self.model_fields_set:
            _dict["activeMessageId"] = None

        # set to None if execution_epoch (nullable) is None
        # and model_fields_set contains the field
        if self.execution_epoch is None and "execution_epoch" in self.model_fields_set:
            _dict["executionEpoch"] = None

        # set to None if execution_started_time (nullable) is None
        # and model_fields_set contains the field
        if self.execution_started_time is None and "execution_started_time" in self.model_fields_set:
            _dict["executionStartedTime"] = None

        # set to None if latest_terminal_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.latest_terminal_message_id is None and "latest_terminal_message_id" in self.model_fields_set:
            _dict["latestTerminalMessageId"] = None

        # set to None if latest_terminal_time (nullable) is None
        # and model_fields_set contains the field
        if self.latest_terminal_time is None and "latest_terminal_time" in self.model_fields_set:
            _dict["latestTerminalTime"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ConversationActivity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "conversationId": obj.get("conversationId"),
                "executionStatus": obj.get("executionStatus"),
                "activeMessageId": obj.get("activeMessageId"),
                "executionEpoch": obj.get("executionEpoch"),
                "executionStartedTime": obj.get("executionStartedTime"),
                "latestTerminalMessageId": obj.get("latestTerminalMessageId"),
                "latestTerminalTime": obj.get("latestTerminalTime"),
                "hasUnreadCompletion": obj.get("hasUnreadCompletion"),
                "requiresUserConfirmation": obj.get("requiresUserConfirmation"),
            }
        )
        return _obj
