# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GeneratePreSignedUrlInput(BaseModel):
    """
    GeneratePreSignedUrlInput 的公开协议结构。 / Public contract for generate pre signed url input.
    """ # noqa: E501
    file_name: Annotated[str, Field(strict=True, max_length=255)] = Field(description="文件名 / file name。", alias="fileName")
    module: StrictStr = Field(description="字段 module / module field。")
    content_md5: Annotated[str, Field(strict=True, max_length=64)] = Field(description="字段 contentMd5 / content md5 field。", alias="contentMd5")
    file_id: Optional[StrictInt] = Field(default=None, description="文件 ID / file ID。", alias="fileId")
    __properties: ClassVar[List[str]] = ["fileName", "module", "contentMd5", "fileId"]

    @field_validator('module')
    def module_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ai-chat-attachments']):
            raise ValueError("must be one of enum values ('ai-chat-attachments')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeneratePreSignedUrlInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if file_id (nullable) is None
        # and model_fields_set contains the field
        if self.file_id is None and "file_id" in self.model_fields_set:
            _dict['fileId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeneratePreSignedUrlInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fileName": obj.get("fileName"),
            "module": obj.get("module"),
            "contentMd5": obj.get("contentMd5"),
            "fileId": obj.get("fileId")
        })
        return _obj


