# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from lingya_agents_sdk.models.default_model import DefaultModel
from lingya_agents_sdk.models.model_key_group import ModelKeyGroup
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ModelConfig(BaseModel):
    """
    ModelConfig 的公开协议结构。 / Public contract for model config.
    """ # noqa: E501
    default_model: Optional[DefaultModel] = Field(description="字段 defaultModel / default model field。", alias="defaultModel")
    model_key_groups: List[ModelKeyGroup] = Field(description="字段 modelKeyGroups / model key groups field。", alias="modelKeyGroups")
    __properties: ClassVar[List[str]] = ["defaultModel", "modelKeyGroups"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of default_model
        if self.default_model:
            _dict['defaultModel'] = self.default_model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in model_key_groups (list)
        _items = []
        if self.model_key_groups:
            for _item_model_key_groups in self.model_key_groups:
                _items.append(_item_model_key_groups.to_dict() if _item_model_key_groups is not None else None)
            _dict['modelKeyGroups'] = _items
        # set to None if default_model (nullable) is None
        # and model_fields_set contains the field
        if self.default_model is None and "default_model" in self.model_fields_set:
            _dict['defaultModel'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "defaultModel": DefaultModel.from_dict(obj["defaultModel"]) if obj.get("defaultModel") is not None else None,
            "modelKeyGroups": [ModelKeyGroup.from_dict(_item) for _item in obj["modelKeyGroups"]] if obj.get("modelKeyGroups") is not None else None
        })
        return _obj


