"""
Lingya Agents OpenAPI

本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.

The version of the OpenAPI document: 0.1.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from pydantic_core import to_jsonable_python
from typing_extensions import Self


class SubagentTaskArtifact(BaseModel):
    """
    SubagentTaskArtifact 的公开协议结构。 / Public contract for subagent task artifact.
    """  # noqa: E501

    artifact_id: StrictStr = Field(description="字段 artifactId / artifact id field。", alias="artifactId")
    name: StrictStr = Field(description="字段 name / name field。")
    mime_type: StrictStr | None = Field(default=None, description="MIME 类型 / MIME type。", alias="mimeType")
    size: Annotated[int, Field(strict=True, ge=0)] | None = Field(
        default=None, description="大小（字节）或分页容量 / byte size or page size。"
    )
    relative_path: StrictStr | None = Field(
        default=None, description="字段 relativePath / relative path field。", alias="relativePath"
    )
    delivery_status: StrictStr = Field(
        description="字段 deliveryStatus / delivery status field。", alias="deliveryStatus"
    )
    issue_codes: list[StrictStr] = Field(description="字段 issueCodes / issue codes field。", alias="issueCodes")
    recoverable: StrictBool = Field(description="字段 recoverable / recoverable field。")
    __properties: ClassVar[list[str]] = [
        "artifactId",
        "name",
        "mimeType",
        "size",
        "relativePath",
        "deliveryStatus",
        "issueCodes",
        "recoverable",
    ]

    @field_validator("delivery_status")
    def delivery_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["NOT_APPLICABLE", "UNVALIDATED", "ACCEPTED", "ACCEPTED_WITH_WARNINGS", "BLOCKED"]):
            raise ValueError(
                "must be one of enum values ('NOT_APPLICABLE', 'UNVALIDATED', 'ACCEPTED', 'ACCEPTED_WITH_WARNINGS', 'BLOCKED')"
            )
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of SubagentTaskArtifact from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if mime_type (nullable) is None
        # and model_fields_set contains the field
        if self.mime_type is None and "mime_type" in self.model_fields_set:
            _dict["mimeType"] = None

        # set to None if size (nullable) is None
        # and model_fields_set contains the field
        if self.size is None and "size" in self.model_fields_set:
            _dict["size"] = None

        # set to None if relative_path (nullable) is None
        # and model_fields_set contains the field
        if self.relative_path is None and "relative_path" in self.model_fields_set:
            _dict["relativePath"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of SubagentTaskArtifact from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "artifactId": obj.get("artifactId"),
                "name": obj.get("name"),
                "mimeType": obj.get("mimeType"),
                "size": obj.get("size"),
                "relativePath": obj.get("relativePath"),
                "deliveryStatus": obj.get("deliveryStatus"),
                "issueCodes": obj.get("issueCodes"),
                "recoverable": obj.get("recoverable"),
            }
        )
        return _obj
