"""
Lingya Agents OpenAPI

本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.

The version of the OpenAPI document: 0.1.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self


class SubagentTask(BaseModel):
    """
    SubagentTask 的公开协议结构。 / Public contract for subagent task.
    """  # noqa: E501

    task_id: StrictStr = Field(description="异步任务 ID / asynchronous task ID。", alias="taskId")
    description: StrictStr = Field(description="可读说明 / human-readable description。")
    subagent_type: StrictStr = Field(description="字段 subagentType / subagent type field。", alias="subagentType")
    status: StrictStr = Field(description="当前状态 / current status。")
    phase: StrictStr | None = Field(default=None, description="字段 phase / phase field。")
    progress_percent: Annotated[int, Field(le=100, strict=True, ge=0)] | None = Field(
        default=None, description="字段 progressPercent / progress percent field。", alias="progressPercent"
    )
    parent_conversation_id: StrictStr = Field(
        description="字段 parentConversationId / parent conversation id field。", alias="parentConversationId"
    )
    parent_message_id: StrictStr = Field(
        description="字段 parentMessageId / parent message id field。", alias="parentMessageId"
    )
    child_conversation_id: StrictStr | None = Field(
        default=None,
        description="字段 childConversationId / child conversation id field。",
        alias="childConversationId",
    )
    child_message_id: StrictStr | None = Field(
        default=None, description="字段 childMessageId / child message id field。", alias="childMessageId"
    )
    result_available: StrictBool = Field(
        description="字段 resultAvailable / result available field。", alias="resultAvailable"
    )
    artifact_count: Annotated[int, Field(strict=True, ge=0)] = Field(
        description="字段 artifactCount / artifact count field。", alias="artifactCount"
    )
    notification_status: StrictStr = Field(
        description="字段 notificationStatus / notification status field。", alias="notificationStatus"
    )
    failure_code: StrictStr | None = Field(
        default=None, description="字段 failureCode / failure code field。", alias="failureCode"
    )
    failure_message: StrictStr | None = Field(
        default=None, description="字段 failureMessage / failure message field。", alias="failureMessage"
    )
    created_time: datetime = Field(description="创建时间 / creation time。", alias="createdTime")
    started_time: datetime | None = Field(
        default=None, description="字段 startedTime / started time field。", alias="startedTime"
    )
    completed_time: datetime | None = Field(
        default=None, description="字段 completedTime / completed time field。", alias="completedTime"
    )
    last_update_time: datetime = Field(description="最后更新时间 / last update time。", alias="lastUpdateTime")
    cancellable: StrictBool = Field(description="字段 cancellable / cancellable field。")
    __properties: ClassVar[list[str]] = [
        "taskId",
        "description",
        "subagentType",
        "status",
        "phase",
        "progressPercent",
        "parentConversationId",
        "parentMessageId",
        "childConversationId",
        "childMessageId",
        "resultAvailable",
        "artifactCount",
        "notificationStatus",
        "failureCode",
        "failureMessage",
        "createdTime",
        "startedTime",
        "completedTime",
        "lastUpdateTime",
        "cancellable",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of SubagentTask from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if phase (nullable) is None
        # and model_fields_set contains the field
        if self.phase is None and "phase" in self.model_fields_set:
            _dict["phase"] = None

        # set to None if progress_percent (nullable) is None
        # and model_fields_set contains the field
        if self.progress_percent is None and "progress_percent" in self.model_fields_set:
            _dict["progressPercent"] = None

        # set to None if child_conversation_id (nullable) is None
        # and model_fields_set contains the field
        if self.child_conversation_id is None and "child_conversation_id" in self.model_fields_set:
            _dict["childConversationId"] = None

        # set to None if child_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.child_message_id is None and "child_message_id" in self.model_fields_set:
            _dict["childMessageId"] = None

        # set to None if failure_code (nullable) is None
        # and model_fields_set contains the field
        if self.failure_code is None and "failure_code" in self.model_fields_set:
            _dict["failureCode"] = None

        # set to None if failure_message (nullable) is None
        # and model_fields_set contains the field
        if self.failure_message is None and "failure_message" in self.model_fields_set:
            _dict["failureMessage"] = None

        # set to None if started_time (nullable) is None
        # and model_fields_set contains the field
        if self.started_time is None and "started_time" in self.model_fields_set:
            _dict["startedTime"] = None

        # set to None if completed_time (nullable) is None
        # and model_fields_set contains the field
        if self.completed_time is None and "completed_time" in self.model_fields_set:
            _dict["completedTime"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of SubagentTask from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "taskId": obj.get("taskId"),
                "description": obj.get("description"),
                "subagentType": obj.get("subagentType"),
                "status": obj.get("status"),
                "phase": obj.get("phase"),
                "progressPercent": obj.get("progressPercent"),
                "parentConversationId": obj.get("parentConversationId"),
                "parentMessageId": obj.get("parentMessageId"),
                "childConversationId": obj.get("childConversationId"),
                "childMessageId": obj.get("childMessageId"),
                "resultAvailable": obj.get("resultAvailable"),
                "artifactCount": obj.get("artifactCount"),
                "notificationStatus": obj.get("notificationStatus"),
                "failureCode": obj.get("failureCode"),
                "failureMessage": obj.get("failureMessage"),
                "createdTime": obj.get("createdTime"),
                "startedTime": obj.get("startedTime"),
                "completedTime": obj.get("completedTime"),
                "lastUpdateTime": obj.get("lastUpdateTime"),
                "cancellable": obj.get("cancellable"),
            }
        )
        return _obj
