# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from lingya_agents_sdk.models.ask_user_question_extension_tool_extension import AskUserQuestionExtensionToolExtension
from lingya_agents_sdk.models.image_generation_extension_tool_extension import ImageGenerationExtensionToolExtension
from lingya_agents_sdk.models.js_run_script_extension_tool_extension import JsRunScriptExtensionToolExtension
from lingya_agents_sdk.models.js_run_script_result_extension_tool_extension import JsRunScriptResultExtensionToolExtension
from lingya_agents_sdk.models.math_formula_extension_tool_extension import MathFormulaExtensionToolExtension
from lingya_agents_sdk.models.math_result_extension_tool_extension import MathResultExtensionToolExtension
from lingya_agents_sdk.models.plan_approval_extension_tool_extension import PlanApprovalExtensionToolExtension
from lingya_agents_sdk.models.skill_resource_extension_tool_extension import SkillResourceExtensionToolExtension
from lingya_agents_sdk.models.sql_chart_result_extension_tool_extension import SqlChartResultExtensionToolExtension
from lingya_agents_sdk.models.sql_query_extension_tool_extension import SqlQueryExtensionToolExtension
from lingya_agents_sdk.models.sql_query_result_extension_tool_extension import SqlQueryResultExtensionToolExtension
from lingya_agents_sdk.models.task_progress_extension_tool_extension import TaskProgressExtensionToolExtension
from lingya_agents_sdk.models.unknown_tool_extension import UnknownToolExtension
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

TOOLEXTENSION_ONE_OF_SCHEMAS = ["AskUserQuestionExtensionToolExtension", "ImageGenerationExtensionToolExtension", "JsRunScriptExtensionToolExtension", "JsRunScriptResultExtensionToolExtension", "MathFormulaExtensionToolExtension", "MathResultExtensionToolExtension", "PlanApprovalExtensionToolExtension", "SkillResourceExtensionToolExtension", "SqlChartResultExtensionToolExtension", "SqlQueryExtensionToolExtension", "SqlQueryResultExtensionToolExtension", "TaskProgressExtensionToolExtension", "UnknownToolExtension"]

class ToolExtension(BaseModel):
    """
    ToolExtension 的公开协议结构。 / Public contract for tool extension.
    """
    # data type: PlanApprovalExtensionToolExtension
    oneof_schema_1_validator: Optional[PlanApprovalExtensionToolExtension] = None
    # data type: AskUserQuestionExtensionToolExtension
    oneof_schema_2_validator: Optional[AskUserQuestionExtensionToolExtension] = None
    # data type: ImageGenerationExtensionToolExtension
    oneof_schema_3_validator: Optional[ImageGenerationExtensionToolExtension] = None
    # data type: SqlQueryExtensionToolExtension
    oneof_schema_4_validator: Optional[SqlQueryExtensionToolExtension] = None
    # data type: SqlQueryResultExtensionToolExtension
    oneof_schema_5_validator: Optional[SqlQueryResultExtensionToolExtension] = None
    # data type: SqlChartResultExtensionToolExtension
    oneof_schema_6_validator: Optional[SqlChartResultExtensionToolExtension] = None
    # data type: MathFormulaExtensionToolExtension
    oneof_schema_7_validator: Optional[MathFormulaExtensionToolExtension] = None
    # data type: MathResultExtensionToolExtension
    oneof_schema_8_validator: Optional[MathResultExtensionToolExtension] = None
    # data type: JsRunScriptExtensionToolExtension
    oneof_schema_9_validator: Optional[JsRunScriptExtensionToolExtension] = None
    # data type: JsRunScriptResultExtensionToolExtension
    oneof_schema_10_validator: Optional[JsRunScriptResultExtensionToolExtension] = None
    # data type: SkillResourceExtensionToolExtension
    oneof_schema_11_validator: Optional[SkillResourceExtensionToolExtension] = None
    # data type: TaskProgressExtensionToolExtension
    oneof_schema_12_validator: Optional[TaskProgressExtensionToolExtension] = None
    # data type: UnknownToolExtension
    oneof_schema_13_validator: Optional[UnknownToolExtension] = None
    actual_instance: Optional[Union[AskUserQuestionExtensionToolExtension, ImageGenerationExtensionToolExtension, JsRunScriptExtensionToolExtension, JsRunScriptResultExtensionToolExtension, MathFormulaExtensionToolExtension, MathResultExtensionToolExtension, PlanApprovalExtensionToolExtension, SkillResourceExtensionToolExtension, SqlChartResultExtensionToolExtension, SqlQueryExtensionToolExtension, SqlQueryResultExtensionToolExtension, TaskProgressExtensionToolExtension, UnknownToolExtension]] = None
    one_of_schemas: Set[str] = { "AskUserQuestionExtensionToolExtension", "ImageGenerationExtensionToolExtension", "JsRunScriptExtensionToolExtension", "JsRunScriptResultExtensionToolExtension", "MathFormulaExtensionToolExtension", "MathResultExtensionToolExtension", "PlanApprovalExtensionToolExtension", "SkillResourceExtensionToolExtension", "SqlChartResultExtensionToolExtension", "SqlQueryExtensionToolExtension", "SqlQueryResultExtensionToolExtension", "TaskProgressExtensionToolExtension", "UnknownToolExtension" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ToolExtension.model_construct()
        error_messages = []
        match = 0
        # validate data type: PlanApprovalExtensionToolExtension
        if not isinstance(v, PlanApprovalExtensionToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PlanApprovalExtensionToolExtension`")
        else:
            match += 1
        # validate data type: AskUserQuestionExtensionToolExtension
        if not isinstance(v, AskUserQuestionExtensionToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AskUserQuestionExtensionToolExtension`")
        else:
            match += 1
        # validate data type: ImageGenerationExtensionToolExtension
        if not isinstance(v, ImageGenerationExtensionToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ImageGenerationExtensionToolExtension`")
        else:
            match += 1
        # validate data type: SqlQueryExtensionToolExtension
        if not isinstance(v, SqlQueryExtensionToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SqlQueryExtensionToolExtension`")
        else:
            match += 1
        # validate data type: SqlQueryResultExtensionToolExtension
        if not isinstance(v, SqlQueryResultExtensionToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SqlQueryResultExtensionToolExtension`")
        else:
            match += 1
        # validate data type: SqlChartResultExtensionToolExtension
        if not isinstance(v, SqlChartResultExtensionToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SqlChartResultExtensionToolExtension`")
        else:
            match += 1
        # validate data type: MathFormulaExtensionToolExtension
        if not isinstance(v, MathFormulaExtensionToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MathFormulaExtensionToolExtension`")
        else:
            match += 1
        # validate data type: MathResultExtensionToolExtension
        if not isinstance(v, MathResultExtensionToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MathResultExtensionToolExtension`")
        else:
            match += 1
        # validate data type: JsRunScriptExtensionToolExtension
        if not isinstance(v, JsRunScriptExtensionToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JsRunScriptExtensionToolExtension`")
        else:
            match += 1
        # validate data type: JsRunScriptResultExtensionToolExtension
        if not isinstance(v, JsRunScriptResultExtensionToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JsRunScriptResultExtensionToolExtension`")
        else:
            match += 1
        # validate data type: SkillResourceExtensionToolExtension
        if not isinstance(v, SkillResourceExtensionToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SkillResourceExtensionToolExtension`")
        else:
            match += 1
        # validate data type: TaskProgressExtensionToolExtension
        if not isinstance(v, TaskProgressExtensionToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TaskProgressExtensionToolExtension`")
        else:
            match += 1
        # validate data type: UnknownToolExtension
        if not isinstance(v, UnknownToolExtension):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UnknownToolExtension`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ToolExtension with oneOf schemas: AskUserQuestionExtensionToolExtension, ImageGenerationExtensionToolExtension, JsRunScriptExtensionToolExtension, JsRunScriptResultExtensionToolExtension, MathFormulaExtensionToolExtension, MathResultExtensionToolExtension, PlanApprovalExtensionToolExtension, SkillResourceExtensionToolExtension, SqlChartResultExtensionToolExtension, SqlQueryExtensionToolExtension, SqlQueryResultExtensionToolExtension, TaskProgressExtensionToolExtension, UnknownToolExtension. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ToolExtension with oneOf schemas: AskUserQuestionExtensionToolExtension, ImageGenerationExtensionToolExtension, JsRunScriptExtensionToolExtension, JsRunScriptResultExtensionToolExtension, MathFormulaExtensionToolExtension, MathResultExtensionToolExtension, PlanApprovalExtensionToolExtension, SkillResourceExtensionToolExtension, SqlChartResultExtensionToolExtension, SqlQueryExtensionToolExtension, SqlQueryResultExtensionToolExtension, TaskProgressExtensionToolExtension, UnknownToolExtension. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into PlanApprovalExtensionToolExtension
        try:
            instance.actual_instance = PlanApprovalExtensionToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AskUserQuestionExtensionToolExtension
        try:
            instance.actual_instance = AskUserQuestionExtensionToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ImageGenerationExtensionToolExtension
        try:
            instance.actual_instance = ImageGenerationExtensionToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SqlQueryExtensionToolExtension
        try:
            instance.actual_instance = SqlQueryExtensionToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SqlQueryResultExtensionToolExtension
        try:
            instance.actual_instance = SqlQueryResultExtensionToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SqlChartResultExtensionToolExtension
        try:
            instance.actual_instance = SqlChartResultExtensionToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MathFormulaExtensionToolExtension
        try:
            instance.actual_instance = MathFormulaExtensionToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MathResultExtensionToolExtension
        try:
            instance.actual_instance = MathResultExtensionToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into JsRunScriptExtensionToolExtension
        try:
            instance.actual_instance = JsRunScriptExtensionToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into JsRunScriptResultExtensionToolExtension
        try:
            instance.actual_instance = JsRunScriptResultExtensionToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SkillResourceExtensionToolExtension
        try:
            instance.actual_instance = SkillResourceExtensionToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TaskProgressExtensionToolExtension
        try:
            instance.actual_instance = TaskProgressExtensionToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UnknownToolExtension
        try:
            instance.actual_instance = UnknownToolExtension.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ToolExtension with oneOf schemas: AskUserQuestionExtensionToolExtension, ImageGenerationExtensionToolExtension, JsRunScriptExtensionToolExtension, JsRunScriptResultExtensionToolExtension, MathFormulaExtensionToolExtension, MathResultExtensionToolExtension, PlanApprovalExtensionToolExtension, SkillResourceExtensionToolExtension, SqlChartResultExtensionToolExtension, SqlQueryExtensionToolExtension, SqlQueryResultExtensionToolExtension, TaskProgressExtensionToolExtension, UnknownToolExtension. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ToolExtension with oneOf schemas: AskUserQuestionExtensionToolExtension, ImageGenerationExtensionToolExtension, JsRunScriptExtensionToolExtension, JsRunScriptResultExtensionToolExtension, MathFormulaExtensionToolExtension, MathResultExtensionToolExtension, PlanApprovalExtensionToolExtension, SkillResourceExtensionToolExtension, SqlChartResultExtensionToolExtension, SqlQueryExtensionToolExtension, SqlQueryResultExtensionToolExtension, TaskProgressExtensionToolExtension, UnknownToolExtension. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AskUserQuestionExtensionToolExtension, ImageGenerationExtensionToolExtension, JsRunScriptExtensionToolExtension, JsRunScriptResultExtensionToolExtension, MathFormulaExtensionToolExtension, MathResultExtensionToolExtension, PlanApprovalExtensionToolExtension, SkillResourceExtensionToolExtension, SqlChartResultExtensionToolExtension, SqlQueryExtensionToolExtension, SqlQueryResultExtensionToolExtension, TaskProgressExtensionToolExtension, UnknownToolExtension]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


