# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from lingya_agents_sdk.models.tool_response import ToolResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ToolResponseChatMessage(BaseModel):
    """
    ToolResponseChatMessage 的公开协议结构。 / Public contract for tool response chat message.
    """ # noqa: E501
    type: StrictStr = Field(description="类型判别值 / type discriminator。")
    responses: List[ToolResponse] = Field(description="字段 responses / responses field。")
    metadata_raw_json: Optional[StrictStr] = Field(default=None, description="字段 metadataRawJson / metadata raw json field。", alias="metadataRawJson")
    __properties: ClassVar[List[str]] = ["type", "responses", "metadataRawJson"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['TOOL']):
            raise ValueError("must be one of enum values ('TOOL')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ToolResponseChatMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in responses (list)
        _items = []
        if self.responses:
            for _item_responses in self.responses:
                _items.append(_item_responses.to_dict() if _item_responses is not None else None)
            _dict['responses'] = _items
        # set to None if metadata_raw_json (nullable) is None
        # and model_fields_set contains the field
        if self.metadata_raw_json is None and "metadata_raw_json" in self.model_fields_set:
            _dict['metadataRawJson'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ToolResponseChatMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "responses": [ToolResponse.from_dict(_item) for _item in obj["responses"]] if obj.get("responses") is not None else None,
            "metadataRawJson": obj.get("metadataRawJson")
        })
        return _obj


