# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from lingya_agents_sdk.models.input_token_breakdown import InputTokenBreakdown
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Usage(BaseModel):
    """
    Usage 的公开协议结构。 / Public contract for usage.
    """ # noqa: E501
    input_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="输入 Token 数 / input token count。", alias="inputTokens")
    output_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="输出 Token 数 / output token count。", alias="outputTokens")
    total_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(description="总 Token 数 / total token count。", alias="totalTokens")
    input_token_breakdown: Optional[InputTokenBreakdown] = Field(default=None, description="字段 inputTokenBreakdown / input token breakdown field。", alias="inputTokenBreakdown")
    reasoning_tokens: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="字段 reasoningTokens / reasoning tokens field。", alias="reasoningTokens")
    cache_hit_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="字段 cacheHitRate / cache hit rate field。", alias="cacheHitRate")
    input_breakdown_coverage_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="字段 inputBreakdownCoverageRate / input breakdown coverage rate field。", alias="inputBreakdownCoverageRate")
    __properties: ClassVar[List[str]] = ["inputTokens", "outputTokens", "totalTokens", "inputTokenBreakdown", "reasoningTokens", "cacheHitRate", "inputBreakdownCoverageRate"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Usage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "total_tokens",
            "cache_hit_rate",
            "input_breakdown_coverage_rate",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input_token_breakdown
        if self.input_token_breakdown:
            _dict['inputTokenBreakdown'] = self.input_token_breakdown.to_dict()
        # set to None if input_token_breakdown (nullable) is None
        # and model_fields_set contains the field
        if self.input_token_breakdown is None and "input_token_breakdown" in self.model_fields_set:
            _dict['inputTokenBreakdown'] = None

        # set to None if reasoning_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.reasoning_tokens is None and "reasoning_tokens" in self.model_fields_set:
            _dict['reasoningTokens'] = None

        # set to None if cache_hit_rate (nullable) is None
        # and model_fields_set contains the field
        if self.cache_hit_rate is None and "cache_hit_rate" in self.model_fields_set:
            _dict['cacheHitRate'] = None

        # set to None if input_breakdown_coverage_rate (nullable) is None
        # and model_fields_set contains the field
        if self.input_breakdown_coverage_rate is None and "input_breakdown_coverage_rate" in self.model_fields_set:
            _dict['inputBreakdownCoverageRate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Usage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "inputTokens": obj.get("inputTokens"),
            "outputTokens": obj.get("outputTokens"),
            "totalTokens": obj.get("totalTokens"),
            "inputTokenBreakdown": InputTokenBreakdown.from_dict(obj["inputTokenBreakdown"]) if obj.get("inputTokenBreakdown") is not None else None,
            "reasoningTokens": obj.get("reasoningTokens"),
            "cacheHitRate": obj.get("cacheHitRate"),
            "inputBreakdownCoverageRate": obj.get("inputBreakdownCoverageRate")
        })
        return _obj


