"""
Lingya Agents OpenAPI

本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.

The version of the OpenAPI document: 0.1.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar, Union

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from lingya_agents_sdk.models.input_token_breakdown import InputTokenBreakdown


class Usage(BaseModel):
    """
    Usage 的公开协议结构。 / Public contract for usage.
    """  # noqa: E501

    input_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(
        description="输入 Token 数 / input token count。", alias="inputTokens"
    )
    output_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(
        description="输出 Token 数 / output token count。", alias="outputTokens"
    )
    total_tokens: Annotated[int, Field(strict=True, ge=0)] = Field(
        description="总 Token 数 / total token count。", alias="totalTokens"
    )
    input_token_breakdown: InputTokenBreakdown | None = Field(
        default=None,
        description="字段 inputTokenBreakdown / input token breakdown field。",
        alias="inputTokenBreakdown",
    )
    reasoning_tokens: Annotated[int, Field(strict=True, ge=0)] | None = Field(
        default=None, description="字段 reasoningTokens / reasoning tokens field。", alias="reasoningTokens"
    )
    cache_hit_rate: Union[StrictFloat, StrictInt] | None = Field(
        default=None, description="字段 cacheHitRate / cache hit rate field。", alias="cacheHitRate"
    )
    input_breakdown_coverage_rate: Union[StrictFloat, StrictInt] | None = Field(
        default=None,
        description="字段 inputBreakdownCoverageRate / input breakdown coverage rate field。",
        alias="inputBreakdownCoverageRate",
    )
    __properties: ClassVar[list[str]] = [
        "inputTokens",
        "outputTokens",
        "totalTokens",
        "inputTokenBreakdown",
        "reasoningTokens",
        "cacheHitRate",
        "inputBreakdownCoverageRate",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Usage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: set[str] = set(
            [
                "total_tokens",
                "cache_hit_rate",
                "input_breakdown_coverage_rate",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input_token_breakdown
        if self.input_token_breakdown:
            _dict["inputTokenBreakdown"] = self.input_token_breakdown.to_dict()
        # set to None if input_token_breakdown (nullable) is None
        # and model_fields_set contains the field
        if self.input_token_breakdown is None and "input_token_breakdown" in self.model_fields_set:
            _dict["inputTokenBreakdown"] = None

        # set to None if reasoning_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.reasoning_tokens is None and "reasoning_tokens" in self.model_fields_set:
            _dict["reasoningTokens"] = None

        # set to None if cache_hit_rate (nullable) is None
        # and model_fields_set contains the field
        if self.cache_hit_rate is None and "cache_hit_rate" in self.model_fields_set:
            _dict["cacheHitRate"] = None

        # set to None if input_breakdown_coverage_rate (nullable) is None
        # and model_fields_set contains the field
        if self.input_breakdown_coverage_rate is None and "input_breakdown_coverage_rate" in self.model_fields_set:
            _dict["inputBreakdownCoverageRate"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of Usage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "inputTokens": obj.get("inputTokens"),
                "outputTokens": obj.get("outputTokens"),
                "totalTokens": obj.get("totalTokens"),
                "inputTokenBreakdown": InputTokenBreakdown.from_dict(obj["inputTokenBreakdown"])
                if obj.get("inputTokenBreakdown") is not None
                else None,
                "reasoningTokens": obj.get("reasoningTokens"),
                "cacheHitRate": obj.get("cacheHitRate"),
                "inputBreakdownCoverageRate": obj.get("inputBreakdownCoverageRate"),
            }
        )
        return _obj
