# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UserInputStatus(BaseModel):
    """
    UserInputStatus 的公开协议结构。 / Public contract for user input status.
    """ # noqa: E501
    pending: StrictBool = Field(description="字段 pending / pending field。")
    question: Optional[StrictStr] = Field(default=None, description="字段 question / question field。")
    question_details: Optional[StrictStr] = Field(default=None, description="字段 questionDetails / question details field。", alias="questionDetails")
    options: Optional[List[StrictStr]] = Field(default=None, description="字段 options / options field。")
    multiple: Optional[StrictBool] = Field(default=None, description="字段 multiple / multiple field。")
    __properties: ClassVar[List[str]] = ["pending", "question", "questionDetails", "options", "multiple"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserInputStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if question (nullable) is None
        # and model_fields_set contains the field
        if self.question is None and "question" in self.model_fields_set:
            _dict['question'] = None

        # set to None if question_details (nullable) is None
        # and model_fields_set contains the field
        if self.question_details is None and "question_details" in self.model_fields_set:
            _dict['questionDetails'] = None

        # set to None if options (nullable) is None
        # and model_fields_set contains the field
        if self.options is None and "options" in self.model_fields_set:
            _dict['options'] = None

        # set to None if multiple (nullable) is None
        # and model_fields_set contains the field
        if self.multiple is None and "multiple" in self.model_fields_set:
            _dict['multiple'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserInputStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pending": obj.get("pending"),
            "question": obj.get("question"),
            "questionDetails": obj.get("questionDetails"),
            "options": obj.get("options"),
            "multiple": obj.get("multiple")
        })
        return _obj


