# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UserInputAnswerInput(BaseModel):
    """
    UserInputAnswerInput 的公开协议结构。 / Public contract for user input answer input.
    """ # noqa: E501
    conversation_id: StrictStr = Field(description="会话 ID / conversation ID。", alias="conversationId")
    message_id: StrictStr = Field(description="消息 ID / message ID。", alias="messageId")
    question_id: StrictStr = Field(description="字段 questionId / question id field。", alias="questionId")
    selected_options: List[StrictStr] = Field(description="字段 selectedOptions / selected options field。", alias="selectedOptions")
    custom_input: Optional[StrictStr] = Field(default=None, description="字段 customInput / custom input field。", alias="customInput")
    __properties: ClassVar[List[str]] = ["conversationId", "messageId", "questionId", "selectedOptions", "customInput"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserInputAnswerInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if custom_input (nullable) is None
        # and model_fields_set contains the field
        if self.custom_input is None and "custom_input" in self.model_fields_set:
            _dict['customInput'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserInputAnswerInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conversationId": obj.get("conversationId"),
            "messageId": obj.get("messageId"),
            "questionId": obj.get("questionId"),
            "selectedOptions": obj.get("selectedOptions"),
            "customInput": obj.get("customInput")
        })
        return _obj


