# coding: utf-8

"""
    Lingya Agents OpenAPI

    Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from lingya_agents_sdk.models.workspace_file_page import WorkspaceFilePage
from lingya_agents_sdk.models.workspace_non_file_artifact import WorkspaceNonFileArtifact
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkspaceArtifactList(BaseModel):
    """
    WorkspaceArtifactList 的公开协议结构。 / Public contract for workspace artifact list.
    """ # noqa: E501
    file_artifacts: WorkspaceFilePage = Field(description="字段 fileArtifacts / file artifacts field。", alias="fileArtifacts")
    non_file_artifacts: List[WorkspaceNonFileArtifact] = Field(description="字段 nonFileArtifacts / non file artifacts field。", alias="nonFileArtifacts")
    __properties: ClassVar[List[str]] = ["fileArtifacts", "nonFileArtifacts"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkspaceArtifactList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of file_artifacts
        if self.file_artifacts:
            _dict['fileArtifacts'] = self.file_artifacts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in non_file_artifacts (list)
        _items = []
        if self.non_file_artifacts:
            for _item_non_file_artifacts in self.non_file_artifacts:
                _items.append(_item_non_file_artifacts.to_dict() if _item_non_file_artifacts is not None else None)
            _dict['nonFileArtifacts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkspaceArtifactList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fileArtifacts": WorkspaceFilePage.from_dict(obj["fileArtifacts"]) if obj.get("fileArtifacts") is not None else None,
            "nonFileArtifacts": [WorkspaceNonFileArtifact.from_dict(_item) for _item in obj["nonFileArtifacts"]] if obj.get("nonFileArtifacts") is not None else None
        })
        return _obj


